### PR TITLE
fix(null-ls): add configuration for null-ls

### PR DESCRIPTION
**Pull request by kylo252**
Had to use dirname for now.

Fixes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/378

### CODE REVIEW

**Comment by mjlbach** [comment]
I don't see the need for this PR, the bug in null-ls has been identified.

**Comment by numToStr** [comment]
I guess this is the real issue: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/378#issuecomment-980065061

**Comment by kylo252** [comment]
Closing in favor of https://github.com/jose-elias-alvarez/null-ls.nvim/pull/379

**Comment by hinell** [comment]
@kylo252 In light of death of `null-ls` and emergence of `none-ls` I suggest to reopen and add saved lspconfig integration.

It was removed from `null-ls` at https://github.com/jose-elias-alvarez/null-ls.nvim/commit/0d038817fd0f4c4298d7c9cf02f13555be8fe647

**Pull request closed without merging**
