### PR TITLE
chore(nix): remove redundant flake-utils dependency; add nix-systems

### PR DESCRIPTION
**Pull request by NotAShelf**
Get rid of flake-utils, add nix-systems support & parameterize over system.

Tested devshell behaviour.

### CODE REVIEW

**Review by jacekpoz — APPROVED** [review]

**Review by Jappie3 — APPROVED** [review]

**Comment by teto** [comment]
how does it differ from what we have now ? does it enable more platforms ? can't we do this with flake-utils ?

**Comment by NotAShelf** [comment]
That's the point: we are trying to get rid of flake utils.

No point in having an entire library as an input when all we're using from its features is a single function that serves only ro abstract system, which we can already do ourselves.

**Review by diniamo — APPROVED** [review]
+1 for removing flake-utils. Even if the flake is more complex, flake-utils is bad. Flake-parts is the only abstraction I would agree to using. In this case though, the flake is simple enough that it could even be replaced by a shell.nix (which you might want to consider if you don't want to add more things to the flake).

**Comment by NotAShelf** [comment]
That is a fair point, we could even get rid of systems input for a genAttrs with some default systems. I don't think the flake.nix is meant for for external party use in this case.

**Review by justinmk — APPROVED** [review]
waiting for @teto approval

**Comment by teto** [comment]
I see this as harmless churn but it seems to make several persons happy so let's go for it.

**Pull request merged**
