### PR TITLE
add filetype in LspInfo floatwindow

### PR DESCRIPTION
**Pull request by glepnir**
@mjlbach  add filetype in lspinfo float window. it will be useful for some indent plugins

### CODE REVIEW

**Comment by mjlbach** [comment]
Seems good to me :)

**Comment by glepnir** [comment]
morning? evening here:)

**Comment by mjlbach** [comment]
Just woke up actually haha, lspsaga beautiful lspinfo replacement when??

**Comment by glepnir** [comment]
just use for my indent-guides plugin. maybe can do  lspinfo window more beautiful in lspsaga .try to implement it later

**Comment by mjlbach** [comment]
I would wait because I can refactor lspinfo so the logic portion is decoupled from the UI portion

**Pull request merged**
