### PR TITLE
docs: recommend LspAttach in readme

### PR DESCRIPTION
**Pull request by ii14**
Most users want to use the same on_attach function for all language servers.

* Bump the required nvim version in the readme to 0.8 (for `LspAttach` event)
* In the suggested configuration replace `on_attach` functions with an `LspAttach` autocommand
* Remove `noremap=true` (it's the default) and `silent=true` (why was it there?) from keymap options
* Remove `{ debounce_text_changes = 150 }` flags (it's the default in 0.8)

### CODE REVIEW

**Comment by glepnir** [comment]
do we need special statement for 0.7version. this event need 0.8

**Comment by mjlbach** [comment]
You all need to take more care merging these sorts of commits. The documentation is now out of sync.

https://github.com/neovim/nvim-lspconfig/blob/master/doc/lspconfig.txt

**Comment by ii14** [comment]
My bad, I wanted to wait for Justin to review it first, I should've put it as a draft.

**Comment by glepnir** [comment]
hmm no my mistake .. i had notice the sync of lspconfig yesterday morning ..but when i merge in afternoon i forget this ..

**Pull request merged**
