### PR TITLE
Update svls description

### PR DESCRIPTION
**Pull request by aklsh**
Description of `svls` has been updated to match the formatting of other language servers.

### CODE REVIEW

**Comment by mjlbach** [comment]
Can you address lint/commit lint errors? Thanks!

**Comment by aklsh** [comment]
Ummm...haven't really followed linting commits - how do I make the commit lint test pass 😅 ? Do I need to amend the commit before making another one?

**Comment by mjlbach** [comment]
You can click on lint/lint to see what need to change.


For the commit message read: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by aklsh** [comment]
@mjlbach  Hopefully I didn't do the rebase wrong 😅. And I removed the white-spaces that caused the lint errors.

**Pull request merged**
