### PR TITLE
Fix markdown oxide root_dir (and update description)

### PR DESCRIPTION
**Pull request by Feel-ix-343**
resolves https://github.com/Feel-ix-343/markdown-oxide/issues/11

### CODE REVIEW

**Comment by glepnir** [comment]
please just edit the lua file doc is generate from ci.

**Comment by justinmk** [comment]
> please just edit the lua file doc is generate from ci.

the PR edits the Lua file, so it doesn't matter if the other files are touched, they'll get regenerated.

**Comment by glepnir** [comment]
>they'll get regenerated.

the doc ci can be removed avoid make confused for first-time contributor.  regenerated anyway.

**Comment by justinmk** [comment]
> the doc ci can be removed avoid make confused for first-time contributor.

We could change its wording. The main purpose (IMO) is to avoid confusion, and to remind people that the Lua code must be updated, and the other files don't need to be.

**Comment by glepnir** [comment]
fair

**Review by justinmk — APPROVED** [review]

**Pull request merged**
