### PR TITLE
fix: update the ansiblels settings

### LINKED ISSUE #2282: Changes in Ansible Language Server configuration
### Description

Configuration options for Ansible Language Server has changed. There is no `ansible.ansibleLint` section anymore, it was replaced by `ansible.validation` section: https://als.readthedocs.io/en/latest/settings/

So default settings look like this now:
```
settings = {
  ansible = {
    python = {
      interpreterPath = 'python',
    },
    ansibleLint = {
      path = 'ansible-lint',
      enabled = true,
    },
    ansible = {
      path = 'ansible',
    },
    executionEnvironment = {
      enabled = false,
    },
  },
}
```

They should look like this:
```
settings = {
  ansible = {
    python = {
      interpreterPath = 'python',
    },
    ansible = {
      path = 'ansible',
    },
    executionEnvironment = {
      enabled = false,
    },
    validation = {
      enabled = true,
      lint = {
        enabled = true,
        path = "ansible-lint"
      }
    },
  },
}
```

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

fcbcc572c4bca765de051e4e75c16db8819376dd

### Operating system and version

Arch Linux

### Affected language servers

ansiblels

### Steps to reproduce

Open any ansible file.

### Actual behavior

Outdated config.

### Expected behavior

_No response_

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = 'ansiblels'
local cmd = { 'ansible-language-server', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
  cmd = cmd,
  on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

no

### PR DESCRIPTION
**Pull request by glepnir**
close #2282

### CODE REVIEW

**Comment by deponian** [comment]
If I understand Ansible language server docs correctly, all settings should stay inside `ansible.*` context: https://github.com/ansible/ansible-language-server/blob/main/docs/settings.md

**Comment by glepnir** [comment]
you can create a pr. I just copy theme from your issue. you give me a wrong example :)

**Comment by deponian** [comment]
Ok, I'll create a PR later today or tomorrow :)

**Comment by deponian** [comment]
Done: https://github.com/neovim/nvim-lspconfig/pull/2286

**Pull request merged**
