### PR TITLE
feat: add golangcilsp support

### PR DESCRIPTION
**Pull request by desdic**
Combination of both lint server and client

https://github.com/nametake/golangci-lint-langserver
https://github.com/golangci/golangci-lint

once/if merged I'll create a pull request on nvim-lsp-installer to make it easy to install

### CODE REVIEW

**Comment by desdic** [comment]
> Can we rename the file to `golangci_ls.lua`? Also would be good if you can add some installation instructions but otherwise looks good assuming tests pass.

Just renamed it .. I can do documentation no problem but I'm adding it to the nvim-lsp-installer (pull request) so maybe that would be ok ?

**Comment by mjlbach** [comment]
There's a large fraction (I would say the majority) of users who don't use nvim-lsp-installer (including myself).

**Comment by mjlbach** [comment]
Actually sorry, golangci_lint_ls instead of golangci_ls

**Comment by desdic** [comment]
> Actually sorry, golangci_lint_ls instead of golangci_ls, didn't realize the language server's name is golangci_lint

Renamed and added 2 commands to install the binaries needed.

**Comment by fipso** [comment]
4FUnkui
 
am i doing something wrong or is lsp broken right now ?

**Comment by mjlbach** [comment]
Did you read the error message? It tells you what is wrong.

**Comment by desdic** [comment]
> 4FUnkui
> 
> am i doing something wrong or is lsp broken right now ?

I think you found the above code on https://github.com/nametake/golangci-lint-langserver right ? I had problems with it too so I made the above patch so you can replace the above with

```
require'lspconfig'.golangci_lint_ls.setup{}
```

or create a custom server .. I did both but decided to make a pull request to make it available for who ever needed it

**Comment by fipso** [comment]
thanks @desdic

**Pull request merged**
