### PR TITLE
feat(solidity): support solang language server

### PR DESCRIPTION
**Pull request by ChristianChiarulli**
This is not a perfect solidity language server but it will at least provide basic diagnostics. 

installing langserver docs: https://solang.readthedocs.io/en/latest/installing.html

^^ download a binary release from above, rename to `solang` and add it to your `PATH`

repo: https://github.com/hyperledger-labs/solang

### CODE REVIEW

**Comment by mjlbach** [comment]
Can you fix lint errors and document the limited capabilities to set expectations low?

**Comment by ChristianChiarulli** [comment]
> Can you fix lint errors and document the limited capabilities to set expectations low?

where is the best place to document this?

**Comment by mjlbach** [comment]
Under docs.description

**Comment by ChristianChiarulli** [comment]
Do I need to open another PR for commit_lint?

**Comment by mjlbach** [comment]
WDYM? I would just rebase/squash with the new message. I would also restructure the docs because there's a bit of duplication:

1. Installation
2. what solidity provides
3. call out what is missing (lose the ellipsis though)
4. 
there's also a duplicated link, this is also parsed into markdown so you can always embed the link like so [google](https://google.com)

**Comment by mjlbach** [comment]
I wanted to modify some things, but you didn't use a feature branch so I made another PR (you're still author)

**Comment by kaykhancheckpoint** [comment]
I am not able to get solidity lsp working in nvim, nothing is being attached, although the solang cli i installed via cargo works fine

**Pull request closed without merging**
