### PR TITLE
Pyright: Add workaround for client/registerCapability for node15

### PR DESCRIPTION
**Pull request by mjlbach**
See: https://github.com/neovim/neovim/issues/13448

closes:   #441

### CODE REVIEW

**Comment by mjlbach** [comment]
@h-michael Do you have thoughts on this? Would it be better to add a generic catch-all callback instead of per-server overrides?

**Comment by h-michael** [comment]
@mjlbach We send dynamicRegistration as false.
But nevertheless, some language servers will send `client/registerCapability`, right?

The specification said that "Server must not register the same capability both statically through the initialize result and dynamically for the same document selector. If a server wants to support both static and dynamic registration it needs to check the client capability in the initialize request and only register the capability statically if the client doesn’t support dynamic registration for that capability."

I think it's against the specs for a server to make this request in the first place as far as I can see, what do you think?

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#client_registerCapability

**Comment by mjlbach** [comment]
@h-michael Yes, in the linked tracking issue I filed against neovim core I noted that several language servers seem to be ignoring this. https://github.com/neovim/neovim/issues/13448

I agree that this should be filed and fixed with the respective defective language servers, however, users are reporting that language servers "aren't working" so I think merging this and #451 until fixes can be pushed upstream would be a good idea. I'll personally make the PR to remove the mitigation.

**Comment by h-michael** [comment]
@mjlbach If we add the ad-hook implementation, I think that it is better to add this implementation to https://github.com/neovim/nvim-lspconfig/blob/f57212075222c18f56a2118ded20632228294249/lua/lspconfig/configs.lua#L36.

**Comment by mjlbach** [comment]
I was going to add it there, but then we don't have a record of the "bad" language servers that need upstream fixes. i'm trying to fix this in pyright now... I don't know how willing microsoft is to merge PRs for non vscode clients (or at least, help debug them)

**Comment by mjlbach** [comment]
@h-michael Filed a bug upstream for pyright https://github.com/microsoft/pyright/issues/1302 I'll add the ad-hook implementation

**Comment by mjlbach** [comment]
See: https://github.com/neovim/nvim-lspconfig/pull/471

**Comment by mjlbach** [comment]
Closing in favor of #471

**Pull request closed without merging**
