### PR TITLE
Fix texlab crash due to missing handler

### LINKED ISSUE #502: Texlab expects window/workDoneProgress/create handler
The latest texlab crashes as it expects a workDoneProgress handler.

cc: @coxackie
```
[ DEBUG ] 2020-12-29T15:19:22-0800 ] ...neovim-nightly-master/share/nvim/runtime/lua/vim/lsp.lua:501 ]	"server_request"	"window/workDoneProgress/create"	{  token = "texlab-build-43c241a6-6335-425a-a0f3-e081e40a82d2"}
[ DEBUG ] 2020-12-29T15:19:22-0800 ] ...neovim-nightly-master/share/nvim/runtime/lua/vim/lsp.lua:504 ]	"server_request: found handler for"	"window/workDoneProgress/create"
[ DEBUG ] 2020-12-29T15:19:22-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:500 ]	"server_request: callback result"	{  result = {},  status = true}
[ DEBUG ] 2020-12-29T15:19:22-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  id = 4,  jsonrpc = "2.0",  result = {}}
[ ERROR ] 2020-12-29T15:19:22-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"texlab"	"stderr"	"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: InvalidParams, message: \"Could not deserialize parameter object\", data: None }', "
[ ERROR ] 2020-12-29T15:19:22-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"texlab"	"stderr"	"/private/tmp/nix-build-texlab-2.2.0.drv-0/source/src/build.rs:98:73\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

### PR DESCRIPTION
**Pull request by mjlbach**
closes #502

@coxackie Can you test this?

### CODE REVIEW

**Comment by coxackie** [comment]
thanks @mjlbach it actually works now. This includes forward search, on top of building. I do not get any linting with chktex, but I will have to check better on this, as it is possible that I have screwed up somewhere in my init. (Using Coc in the meantime, before lsp becomes more stable). Anyway, I think you should merge, it is already much better...

**Comment by mjlbach** [comment]
> Using Coc in the meantime, before lsp becomes more stable
don't give up on us yet! I need your bug reports :P

**Comment by coxackie** [comment]
Lol. I don't intend to. Heavily rooting for you. It is just that I also have to work, so I will use the necessary evil until better times. That I can see arriving...

**Comment by coxackie** [comment]
ok, quickly leaving this here before I open new issues, as there may be a quick fix: I cannot get snippets to work from `nvim-vsnip`, using also `nvim-completion`. They work for `R` and `Rust`; the mapped key <C-j> triggers their expansion, but for tex files <C-j> in insert mode just changes line. I noticed that you put a lot more defaults in this commit, and one of them is snippetSupport off - even when I enabled it
```
   capabilities = {
        completion = {
          completionItem = {
            snippetSupport = true,
          }
        }
    },
```
nothing happens still. If there is no easy answer, I will open a new ticket.

**Pull request merged**
