### PR TITLE
Add Selene linter

### PR DESCRIPTION
**Pull request by lithammer**
https://github.com/Kampfkarren/selene

### CODE REVIEW

**Comment by mjlbach** [comment]
@lithammer would you mind rebasing this and seeing how bad the damage is/what we would have to change? Last time I remember a lotttt of red.

**Comment by mjlbach** [comment]
are you psychic, I literally just opened this PR to rebase it haha

**Comment by lithammer** [comment]
Hah! Gotta find a reason to _not_ work 😉 Anyway, seems like it doesn't have much to complain about anymore. Just some unused variables:

```
warning[unused_variable]: j is defined, but never used
   ┌─ lua/lspconfig/rust_analyzer.lua:28:30
   │
28 │         on_stdout = function(j, d, e)
   │                              ^

warning[unused_variable]: e is defined, but never used
   ┌─ lua/lspconfig/rust_analyzer.lua:28:36
   │
28 │         on_stdout = function(j, d, e)
   │                                    ^

warning[unused_variable]: j is defined, but never used
   ┌─ lua/lspconfig/rust_analyzer.lua:31:30
   │
31 │         on_stderr = function(j, d, e)
   │                              ^

warning[unused_variable]: e is defined, but never used
   ┌─ lua/lspconfig/rust_analyzer.lua:31:36
   │
31 │         on_stderr = function(j, d, e)
   │                                    ^

warning[unused_variable]: s is defined, but never used
    ┌─ lua/lspconfig/util.lua:189:23
    │
189 │     local function it(s, v)
    │                       ^
```

**Comment by mjlbach** [comment]
Andddd we should probably fix those. Can we move the selene config files out of the top level of the repo and then add the selene lint to make lint?

**Comment by lithammer** [comment]
> Can we move the selene config files out of the top level of the repo

A downside with that is it will break editor integration. But I'm fine either way.

>  [...] and then add the selene lint to make lint?

It should already be there. Or were you thinking of something else?

**Comment by mjlbach** [comment]
> A downside with that is it will break editor integration. But I'm fine either way.

You made this point in the neovim core formatting check too, but this time I conceed :)

**Comment by lithammer** [comment]
> > A downside with that is it will break editor integration. But I'm fine either way.
> 
> You made this point in the neovim core formatting check too, but this time I conceed :)

Indeed! You win some, you lose some 🤷‍♂️

**Comment by mjlbach** [comment]
At this point I am amazed at the level of CI we have in the repo *without* implementing server specific tests 😆

**Pull request merged**
