### PR TITLE
Fix minor typo in sumneko_lua instructions

### PR DESCRIPTION
**Pull request by akinsho**
Just a small typo fix

### CODE REVIEW

**Comment by mjlbach** [comment]
Thanks!

**Comment by mjlbach** [comment]
Wait, I shouldn't have merged this. This is a typo in CONFIG.md, it's auto-generated. I thought you had done in it the sumneko_lua. For future reference, don't edit it in CONFIG.md.

**Comment by akinsho** [comment]
Woops sorry I hadn't realised, I was just reading through on the web and changed it there

**Comment by mjlbach** [comment]
It's ok haha, we got 3 separate PRs doing the same :) I added the warning more explicitly to the PR template.

**Pull request merged**
