### PR TITLE
feat: add pyre language server.

### PR DESCRIPTION
**Pull request by nemith**
Pyre is yet another static type checker for python. https://pyre-check.org/

### CODE REVIEW

**Comment by mjlbach** [comment]
Thanks! Can you add some installation instructions, and possibly copy some of the root detection logic from pyright?

**Comment by mjlbach** [comment]
Currently when I run this, I get
```
LSP[pyre]: Error NO_RESULT_CALLBACK_FOUND: {                               
  id = 0,                                                                  
  jsonrpc = "2.0",                                                         
  result = {                                                               
    capabilities = {}                                                      
  }                                                                        
}
```

Which indicates pyre might be doing something nonstandard, need to look into it

**Comment by nemith** [comment]
I have only tested this on pyre initialized repositories (i.e pyre init) has been ran.  I haven't tested at all on code that isn't initialized and may just fail like above.  Also why i didn't include other root detection logic.

**Comment by mjlbach** [comment]
Yes, I'm having some issues getting it to work even after initializing pyre for a project. Missing imports, dying language server, etc... Pyright works fine with the same project.

**Pull request merged**
