### PR TITLE
feat: add qml-lsp support

### PR DESCRIPTION
**Pull request by poperigby**
I wasn't entirely sure if globbing is support with `util.root_pattern`, but all the tests passed.

### CODE REVIEW

**Comment by lithammer** [comment]
Please format with [StyLua](https://github.com/JohnnyMorganz/StyLua).

**Comment by poperigby** [comment]
Oops, the commit message failed. How should I fix that with out needing a force push?

**Comment by lithammer** [comment]
Squashing and force pushing is fine.

**Comment by poperigby** [comment]
@lithammer I think this should be good now.

**Comment by poperigby** [comment]
@lithammer There actually appear to be a few problems with this setup? Should I open a new issue?

**Comment by lithammer** [comment]
> @lithammer There actually appear to be a few problems with this setup? Should I open a new issue?

Or pull request if you know how to fix them.

**Pull request merged**
