### PR TITLE
feat: update gdscirpt cmd by using 0.8 api

### LINKED ISSUE #2171: Switch gdscript to the new native TCP support instead of using netcat
### Language server

gdscript

### Requested feature

Nvim 0.8 introduced `vim.lsp.rpc.connect`

Current gdscript command is `{ 'nc', 'localhost', '6008' }`
An [example](https://zignar.net/2022/10/01/new-lsp-features-in-neovim-08/#tcp-support) of using that in this case can be found here

### Other clients which have this feature

_No response_

### PR DESCRIPTION
**Pull request by glepnir**
using 0.8 api in gdscript `cmd` .

@RaafatTurki  can you test this PR.

Fix #2171

### CODE REVIEW

**Comment by RaafatTurki** [comment]
This has to be one of the fastest PRs, It works just as before!

**Comment by glepnir** [comment]
Thanks for test :)

**Comment by A-Lamia** [comment]
This does not work for me on windows.


```
[START][2022-10-05 15:03:42] LSP logging initiated
[WARN][2022-10-05 15:03:42] .../lua\vim\lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-10-05 15:03:42] .../lua\vim\lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
```

**Comment by glepnir** [comment]
check the log . looks like there no handler of request method of `workspace/diagnostic/refresh` . this pr just change the cmd  field. does this relate?

**Comment by A-Lamia** [comment]
localhost seems to cause issues but replacing it with 127.0.0.1 seems to fix one of the errors.

**Comment by A-Lamia** [comment]
@glepnir yeah i have no idea why, i get an error saying the IP is incorrect but when i replace it no issue at all. Now im dealing with an issue where i can see in godot a connection is made but thats it nothing else is working no error messages  or auto complete. 

bellow was the example given.

```lua
  vim.lsp.start {
    name = "godot",
    cmd = vim.lsp.rpc.connect("127.0.0.1", 6008), -- Port must match your Language server settings within Godot
    root_dir = vim.fs.dirname(vim.fs.find({ "project.godot" }, { upward = true })[1]),
  }

```

**Comment by glepnir** [comment]
I know nothing about gdscript . but if change to 127 can works well for anyone .  change it :)

**Comment by AbdurahmanTumgaev** [comment]
I have the exact same behaviour as @A-Lamia when using `vim.lsp.rpc.connect`

**Comment by DasGandlaf** [comment]
I have the exact same issue, and I too was only able to fix it with ncat. I tried using localhost, and 127.0.0.1 with `vim.lsp.rpc.connect` but neither worked. Only using ncat works.

**Comment by DasGandlaf** [comment]
@A-Lamia Where you able to make it work with `vim.lsp.rpc.connect`?

**Comment by A-Lamia** [comment]
@DasGandlaf I gave up shortly after this post and stuck with Ncat, if it aint broke don't fix it. I don't even know if this LSP config works for anyone or the majority.

**Comment by DasGandlaf** [comment]
Ah, ok I see. I wasn't able to make it work either :/

**Pull request merged**
