### PR TITLE
docs(lua_ls): config hint how to prevent popups

### PR DESCRIPTION
**Pull request by matu3ba**
See
https://github.com/LuaLS/lua-language-server/issues/679#issuecomment-925524834 for context.

Problem: Multiple prompts show up:
```
1: Apply and modify settings
2: Apply but do not modify settings
3: Don't show again
Type number and <Enter> or click with the mouse (q or empty cancels):
```

Fix: Use
```json
settings = {
  Lua = {
    workspace = {
      checkThirdParty = false,
    },
  },
}
```

### CODE REVIEW

**Comment by glepnir** [comment]
this option default is false. and i think it has been removed in latest luals.

**Comment by matu3ba** [comment]
> and i think it has been removed in latest luals.

At least for `installed version 3.6.18` when I check in Mason not (configured with zero-lsp) not.
Are you using master with HEAD?

From given config
```lua
lsp.configure('lua_ls', {
  settings = {
    Lua = {
      runtime = {
        -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
        version = 'LuaJIT',
        -- path = runtime_path,
      },
      diagnostics = {
        -- Get the language server to recognize the `vim` global
        globals = {'vim'},
      },
      workspace = {
        -- Make the server aware of Neovim runtime files
        library = vim.api.nvim_get_runtime_file("", true),
        checkThirdParty = false,
      },
      -- Do not send telemetry data containing a randomized but unique identifier
      telemetry = {
        enable = false,
      },
    },
  },
  force_setup = true,
})
```
this check also shows me that its needed:
`:lua require('lsp-zero.check').inspect_settings('lua_ls')`
```
{
  Lua = {
    diagnostics = {
      globals = { "vim" }
    },
    runtime = {
      version = "LuaJIT"
    },
    telemetry = {
      enable = false
    },
    workspace = {
      checkThirdParty = false,
      library = { "/home/user/.config/nvim", "/home/user/.local/share/nvim/lazy/lazy.nvim", "/home/mister
spoon/.local/share/nvim/lazy/telescope-undo.nvim", "/home/user/.local/share/nvim/lazy/mini.move", "/home/misters
poon/.local/share/nvim/lazy/gitsigns.nvim", "/home/user/.local/share/nvim/lazy/vim-fugitive", "/home/user
/.local/share/nvim/lazy/nvim-surround", "/home/user/.local/share/nvim/lazy/nvim-osc52", "/home/user/.loca
l/share/nvim/lazy/mini.indentscope", "/home/user/.local/share/nvim/lazy/undotree", "/home/user/.local/sha
re/nvim/lazy/mini.align", "/home/user/.local/share/nvim/lazy/material.nvim", "/home/user/.local/share/nvi
m/lazy/mini.bracketed", "/home/user/.local/share/nvim/lazy/mini.ai", "/home/user/.local/share/nvim/lazy/d
iffview.nvim", "/home/user/.local/share/nvim/lazy/leap.nvim", "/home/user/.local/share/nvim/lazy/venn.nvi
m", "/home/user/.local/share/nvim/lazy/nvim-treesitter", "/home/user/.local/share/nvim/lazy/iswap.nvim",
"/home/user/.local/share/nvim/lazy/telescope-zf-native.nvim", "/home/user/.local/share/nvim/lazy/vim-nix"
, "/home/user/.local/share/nvim/lazy/harpoon", "/home/user/.local/share/nvim/lazy/plenary.nvim", "/home/m
isterspoon/.local/share/nvim/lazy/popup.nvim", "/home/user/.local/share/nvim/lazy/telescope.nvim", "/home/mister
spoon/.local/share/nvim/lazy/nvim-lint", "/home/user/.local/share/nvim/lazy/telescope-github.nvim", "/home/miste
rspoon/.local/share/nvim/lazy/cmp_luasnip", "/home/user/.local/share/nvim/lazy/friendly-snippets", "/home/mister
spoon/.local/share/nvim/lazy/cmp-path", "/home/user/.local/share/nvim/lazy/cmp-nvim-lua", "/home/user/.lo
cal/share/nvim/lazy/cmp-buffer", "/home/user/.local/share/nvim/lazy/LuaSnip", "/home/user/.local/share/nv
im/lazy/cmp-nvim-lsp", "/home/user/.local/share/nvim/lazy/nvim-cmp", "/home/user/.local/share/nvim/lazy/m
ason-lspconfig.nvim", "/home/user/.local/share/nvim/lazy/mason.nvim", "/home/user/.local/share/nvim/lazy/
nvim-lspconfig", "/home/user/.local/share/nvim/lazy/lsp-zero.nvim", "/home/user/.local/share/nvim/lazy/hy
dra.nvim", "/home/user/.local/share/nvim/lazy/oil.nvim", "/home/user/.local/share/nvim/lazy/which-key.nvi
m", "/home/user/.local/share/nvim/lazy/cmp-cmdline", "/home/user/.local/share/nvim/lazy/zig.vim", "/home/
user/.local/share/nvim/lazy/Comment.nvim", "/home/user/projects/buf.nvim", "/home/user/.local/nvim
/share/nvim/runtime", "/home/user/.local/nvim/share/nvim/runtime/pack/dist/opt/matchit", "/home/user/.loc
al/nvim/lib/nvim", "/home/user/.local/state/nvim/lazy/readme", "/home/user/.local/share/nvim/lazy/cmp_lua
snip/after", "/home/user/.local/share/nvim/lazy/cmp-path/after", "/home/user/.local/share/nvim/lazy/cmp-n
vim-lua/after", "/home/user/.local/share/nvim/lazy/cmp-buffer/after", "/home/user/.local/share/nvim/lazy/
cmp-nvim-lsp/after", "/home/user/.local/share/nvim/lazy/cmp-cmdline/after" }
    }
  }
}
```

Here is the default settings, which only has only telemetry disabled:
https://github.com/neovim/nvim-lspconfig/blob/94291c924f0efdbc16ac625cf77ae7d3a7fa5821/lua/lspconfig/server_configurations/lua_ls.lua

**Comment by glepnir** [comment]
you can config it in your local right ? why it must in lspconfig setting ?

**Comment by matu3ba** [comment]
Yes, its just nicer experience to not having to search through issues to get it fixed.

**Pull request closed without merging**
