### PR TITLE
Add support for "Svelte" language server

### PR DESCRIPTION
**Pull request by elianiva**
I can't check if the docs is properly generated though. I think it 'should' work because I copied them from `tsserver.lua` but after running `scripts/docgen.lua` like the [CONTRIBUTING.md](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#generating-docs) says and nothing happens. (to be fair, it downloads stuff but after that nothing happens/changed).

https://github.com/sveltejs/language-tools/tree/master/packages/language-server

### CODE REVIEW

**Comment by snorkysnark** [comment]
Hi! Looks like it's installing typescript-language-server, not svelte. Did you forget to replace?

**Comment by elianiva** [comment]
oh my, how did I not notice that xD
thanks for correcting it!

**Comment by mikegolod** [comment]
Cool! Waiting for this to be released!

**Comment by bkegley** [comment]
Outside of this needing to be moved to the `lua/lspconfig` directory instead is there anything that's preventing this from getting merged? Would love this!

**Comment by mjlbach** [comment]
@elianiva can you fix the nvim_lsp -> lspconfig rename?

**Comment by elianiva** [comment]
Oh, my bad. Turns out I only renamed the thing and forgot to move the folder, fixed it!

**Comment by mikegolod** [comment]
Huge thanks! Using this already!

**Pull request merged**
