### PR TITLE
New docgen with mkdocs (online documentation) support (#1027)

### PR DESCRIPTION
**Pull request by andersevenrud**
The following PR introduces some changes in order to generate markdown files that is optimized for use with mkdocs. 

## Changes

- New docgen
- Adds `language_name` to the configuration files (ex.: `Python`)
- Produce individual markdown files in addition to `CONFIG.md`
- Produce [MkDocs](https://www.mkdocs.org/) configuration

### :warning: Required migrations :warning: 

This PR introduces new metadata to the LSP configurations that is required:

```lua
config.server_name = {
  docs = {
    -- This is used for the markdown generation
    -- Shown as: `Server Language (server_name)`
    language_name = "Server Language" 
  }
}
```

## How to test

I've put up a demo here: https://andersevenrud.github.io/nvim-lspconfig-web/configurations/pyls/

```shell
pip install mkdocs-material # this also installs peer dependencies
./scripts/docgen.sh
mkdocs serve
```

## TODO

- [ ] Improve language names assigned in the metadata
- [ ] Github action for Github pages
- [ ] ... see discussion topics below ...

## Discussion topics

1. This tries to keep backwards compability in the `CONFIG.md` file. Should this be removed and instead point users towards the split versions ?
3. The `<details>` elements did not support markdown, so they were removed in the web versions. But because of the template changes this is maybe not much of an issue?
4. The contents of ex. `README.md` has now been duplicated, which is probably not ideal.

## Relevant issues

- https://github.com/neovim/nvim-lspconfig/issues/1027

### CODE REVIEW

**Comment by andersevenrud** [comment]
Re-opened from #1036  because I managed to do a bad rebase and the bot kicked me out :sweat_smile:

**Comment by TeoDev1611** [comment]
How can help to the documentation?

**Comment by andersevenrud** [comment]
@TeoDev1611 I think it's best that @mjlbach takes a look at this before proceeding to update and improve this PR.

I was going to ping him, but I've been a bit busy and it slipped my mind... but now he'll get a message :blush:

**Comment by mjlbach** [comment]
Hi, I am alive.

I'm debating what to do and where to put this in response to Justin's feedback. I want the website but I want it to be a subdomain/coherent with the rest of the neovim website (which itself may need an overhaul some attention). For now I am considering independently hosting it as a non-official thing. I think the website should be in a separate repo from lspconfig, possibly nvim-lua (which I am also an org owner of now).

**Comment by TeoDev1611** [comment]
Good when you need help can you ping me ? 👍

**Comment by andersevenrud** [comment]
@mjlbach I see. I'd be happy to look into integrating this into the main website (which indeed looks like it needs some love).

**Comment by TeoDev1611** [comment]
I have a idea 💡

If make a Organization called "Neovim Docs" or something like that ?

For make documentation web for the help needed into the new lua features.

- Migration Guides
- Packages Managers
- Native Lsp setup
- Completion frameworks
- etc.
Is a good idea or not ? 🤔

**Comment by mjlbach** [comment]
@TeoDev1611 I'd prefer to update the documentation in lspconfig (especially the wiki) if users are having specific issues. I think the wiki is fairly comprehensive now.

**Comment by TeoDev1611** [comment]
@mjlbach Well I check if can make a best documentation in the wiki for help to the users 👍🏼

**Comment by mjlbach** [comment]
>  a best documentation in the wiki for help to the users 

I'm not sure what this means, I would suggest pointing out specific areas of improvement first and then I can make the changes.

**Comment by TeoDev1611** [comment]
> > a best documentation in the wiki for help to the users
> 
> I'm not sure what this means, I would suggest pointing out specific areas of improvement first and then I can make the changes.

I'm sorry if I didn't make myself clear, I meant exactly what you said.

**Comment by andersevenrud** [comment]
@mjlbach I did a thing...

https://github.com/andersevenrud/neovim.github.io (deployed at https://andersevenrud.github.io/neovim.github.io/)

The LSP documentation from this PR is a sub-site that you can navigate to via the `Documentation > LSP` page.

**Comment by TeoDev1611** [comment]
@andersevenrud  Awesome work in the documentation 👍🏼 😎

**Comment by clason** [comment]
Does (or will) this include https://github.com/neovim/nvim-lspconfig/blob/master/ADVANCED_README.md and the info from the Wiki (which should be consolidated)?

**Comment by mjlbach** [comment]
These are intentionally not consolidated

**Comment by mjlbach** [comment]
Can you move this to a repo in `nvim-lsp`?

**Comment by andersevenrud** [comment]
@mjlbach Just point me to the place and I will see what I can do about transfering this stuff :blush:

**Comment by mjlbach** [comment]
You should have an invite now :)

**Pull request closed without merging**
