### PR TITLE
fix(help): workaround plugin/users overwritting tags

### LINKED ISSUE #1507: Regenerating helptags dirties the repo
### Description

This was introduced in  #1497
Whenever you run `helptags` on `nvim-lspconfig`, the geterated tags file will differ from the one checked into the repo.
I think a lot of people might be generating their helptags on their own as well.
Since I have `nvim-lspconfig` as a subrepo [here](https://github.com/perrin4869/dotfiles/tree/master/home/.local/share/nvim/site/pack/default/start), my own repo becomes dirty after generating the tags

### Neovim version

NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.0.5
Compiled by root@landau.julian.dotcore.co.il

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

d9aa848d

### Operating system and version

slackware64-current

### Affected language servers

none

### Steps to reproduce

Running `helptags ALL` inside neovim with `nvim-lspconfig`.

### Actual behavior

`nvim-lspconfig` repo becomes dirty

### Expected behavior

`nvim-lspconfig` files do not change from the committed versions

### Minimal config

```Lua
Not relevant?
```

### Health check

Not relevant?

### LSP log

not relevant

### PR DESCRIPTION
**Pull request by muniter**
<details>
<summary>Previous solution</summary>

Most plugin managers run `:helptags` in the plugin, which silently
overwrites the existing `doc/tags`. this is an issue for us since lspconfig
is manipulating the tags file to point to servers_configurations.md

By renaming the tags file as `tags-en` `:helptags` won't overwrite it since
there's no lspconfig.enx help file. Now when `:helptags` is run in
lspconfig it will generate `doc/tags` missing the cherry picked tag, but
`:help` will always look (from my testing) into `tags-en`. So everything
should work well.
</details>

Most plugin managers run :helptags in the plugin, which silently
overwrites the existing doc/tags. this is an issue for us since lspconfig
is manipulating the tags file to point to servers_configurations.md

Instead create a markdown comment with the name of the wanted tag and
make a copy in the repository of servers_configurations.md to
server_configurations.txt. Now when :helptags runs it finds the txt file
and generates the appropriate tag.

The advantage is this solution should work in all platforms, it also
removes lines from docgen CI.

fixes #1507

### CODE REVIEW

**Comment by mjlbach** [comment]
@perrin4869 does this address your issue?

**Comment by muniter** [comment]
https://user-images.githubusercontent.com/9699804/143923766-089821e9-13a2-42a5-9877-f677124416a8.mp4

Quick video from barebones neovim, It gives an error message when going to the tag but still does it weirdly. Might be a blocker?

**Comment by mjlbach** [comment]
Maybe the txt solution but I hate it.

**Comment by muniter** [comment]
Duplicating the server config file is ugly but guaranteed to work with no errors. At the end of the day git is doing deduplication and in the filesystem it's a few kb.

We can also completely remove all the new logic in docgen. And since the file is automatically generated no worries on being out of date.

**Comment by mjlbach** [comment]
That's fine then. let's just do it.

**Comment by perrin4869** [comment]
Yeah this doesn't change the helptags anymore, but `:help lspconfig-server-configurations` doesn't seem to be available under this branch

**Comment by muniter** [comment]
> Yeah this doesn't change the helptags anymore, but `:help lspconfig-server-configurations` doesn't seem to be available under this branch

Yeah, the `txt` file will be generated by CI  in the master bran once this is merged.

**Pull request merged**
