### PR TITLE
fix(beancount): remove --stdio arg

### PR DESCRIPTION
**Pull request by williamboman**
Seems like the `--stdio` arg is not needed:

```
[ERROR][2022-04-12 18:39:14] .../vim/lsp/rpc.lua:420	"rpc"	"beancount-langserver"	"stderr"	"error: Found argument '--stdio' which wasn't expected, or isn't valid in this context\n\n\tIf you tried to supply `--stdio` as a value rather than a flag, use `-- --stdio`\n\nUSAGE:\n    beancount-langserver\n\nFor more information try --help\n"
```

https://github.com/polarmutex/beancount-language-server#installation

### CODE REVIEW

**Comment by mjlbach** [comment]
? https://github.com/neovim/nvim-lspconfig/pull/1791

**Comment by polarmutex** [comment]
I really need to update the README (sorry) . 

I have the node version in a branch( still works but I am not planning on adding features),  but I am planning on switching to rust soon (fully working but really have not released it yet, so currently it is installed only from source). 

I could make the options the same so you could use either one or go ahead and drop the option and I can get the rust version in the crates.io registry. I have not heard much feedback on the current rust version and if it is working well I can start making the switch

**Comment by mjlbach** [comment]
It doesn't matter to me, just let me know whether or not I should merge the PR and I will :)

**Comment by williamboman** [comment]
> I could make the options the same so you could use either one or go ahead and drop the option and I can get the rust version in the crates.io registry. I have not heard much feedback on the current rust version and if it is working well I can start making the switch

I think it would make sense to do this!

I noticed that the Rust implementation seems to take the following structure:

```
journal_file: String
```

whereas the settings in lspconfig (and I assume this is how the "old" TS implementation worked) uses the following structure:

```
journalFile: String
pythonPath: String
```

Maybe it could be nice for the Rust impl to use the same casing for `journalFile`?

I'm also running into some errors in automated tests over at https://github.com/williamboman/nvim-lspconfig-test/blob/develop/tests/beancount/lsp_spec.lua. It uses the binary provided via GitHub releases to run the server.

Here are neovim's client LSP logs after running 

```
$ TEST=beancount make setup
$ RUST_BACKTRACE=full TEST=beancount make test
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/server.rs:
81:97
stack backtrace:

   0:        0x104e6ba21 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c059b532d34bdd
   1:        0x104e89e6b - core::fmt::write::hefb311138778afb5
   2:        0x104e673ba - std::io::Write::write_fmt::h0e0ed87b18ae870c
   3:        0x104e6d2b5 - std::panicking::default_hook::{{closure}}::h43f0e51e5825bd5b
   4:        0x104e6ce9f - std::panicking::default_hook::ha1c3473cbcf391f7
   5:        0x104e6d9a0 - std::panicking::rust_panic_with_hook::h0db3c4ba5fb4dc12
   6:        0x104e6d43e - std::panicking::begin_panic_handler::{{closure}}::hc6d8c92efeef5a19
   7:        0x104e6be97 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ffb59e898e02a83
   8:        0x104e6d3aa - _rust_begin_unwind
   9:        0x104ea9e2f - core::panicking::panic_fmt::h7d73f67464d78916
  10:        0x104ea9f15 - core::result::unwrap_failed::h0731520e33902c09
  11:        0x104c32f2d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdbfd74095fb658fd
  12:        0x104d6ae52 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0b2920a08c2fff77
  13:        0x104c38087 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h7ef259501d048329
  14:        0x104bd8045 - futures_util::stream::stream::StreamExt::poll_next_unpin::h0551294a368372e4
  15:        0x104bcbbcb - futures_util::stream::stream::StreamExt::poll_next_unpin::he82aa93300269637
  16:        0x104c393c2 - <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next::h31dfc8fde3656629
  17:        0x104bb9555 - <futures_util::stream::select_with_strategy::SelectWithStrategy<St1,St2,Clos,State> as futures_core::stream::Stream>::poll_next::hf245d65e6df88f9f
  18:        0x104c37fd8 - <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h5cd94fcc7f13302c
  19:        0x104bac02e - <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll::h20645ba8f94c166b
  20:        0x104bb8e81 - <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll::h322df37f0724e775
  21:        0x104c07d55 - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hf0149c8b8d4a0f5b
  22:        0x104c2c4f8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6d39a5978779adfb
  23:        0x104c05415 - tokio::park::thread::CachedParkThread::block_on::hb0d3b6da3a509650
  24:        0x104c05641 - tokio::runtime::thread_pool::ThreadPool::block_on::h68766fb78fc2c5c4
  25:        0x104bb5e1b - tokio::runtime::Runtime::block_on::h159679301d082605
  26:        0x104c37e67 - beancount_language_server::main::h425bc04982ca4dc7
  27:        0x104bf7f26 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6186feaaef90547b
  28:        0x104bada51 - std::rt::lang_start::{{closure}}::h64a079ebefd0676a
  29:        0x104e6b6cf - std::rt::lang_start_internal::hb74872162e3d56c9
  30:        0x104c37fb9 - _main
```

**Comment by mjlbach** [comment]
@polarmutex should I merge this?

**Comment by polarmutex** [comment]
I think the consensus is we will not merge this and I will make both the typescript and rust version use the same options @williamboman

**Comment by williamboman** [comment]
#1879

**Pull request closed without merging**
