### PR TITLE
Typo fixed from fluttre to flutter in README.md and dartls.lua

### PR DESCRIPTION
**Pull request by himansingh241**

### CODE REVIEW

**Comment by lithammer** [comment]
Probably want to update the implementation as well:

https://github.com/neovim/nvim-lsp/blob/fc9d94ef006e082596c2e8724eb3f1c92ff203c7/lua/nvim_lsp/dartls.lua#L40

**Comment by himansingh241** [comment]
> Probably want to update the implementation as well:
> 
> https://github.com/neovim/nvim-lsp/blob/fc9d94ef006e082596c2e8724eb3f1c92ff203c7/lua/nvim_lsp/dartls.lua#L40

Done

**Comment by himansingh241** [comment]
@lithammer Sorry to disturb you but are the PR's not being merged for now?

**Comment by lithammer** [comment]
Sorry, I'm not actually a maintainer. I just do some occasional "drive-by reviewing".

**Pull request merged**
