### PR TITLE
feat: add docker-compose-language-service support

### PR DESCRIPTION
**Pull request by marcdeop**
Potentially [related](https://github.com/williamboman/mason.nvim/pull/986)

### CODE REVIEW

**Review by williamboman — COMMENTED** [review]
It's worth noting that the npm package itself doesn't provide an executable (it would probably be a good idea to request they do so, if someone feels like creating an issue with them). The executable used in this PR is currently only provided by mason.nvim - maybe it'd be good to omit the `cmd` until an official one is provided upstream?

**Comment by marcdeop** [comment]
Request for the `cmd` [here](https://github.com/microsoft/compose-language-service/issues/114)

**Comment by gegoune** [comment]
Thanks for that! Seems like that executable is called `docker-compose-langserver` on MacOS.

**Comment by marcdeop** [comment]
> Thanks for that! Seems like that executable is called `docker-compose-langserver` on MacOS.

Yes, we coordinated yesterday with upstream.

I will submit a PR shortly

**Comment by marcdeop** [comment]
[PR](https://github.com/neovim/nvim-lspconfig/pull/2458)

**Pull request merged**
