### PR TITLE
fix(checkhealth): rename check_health to check

### PR DESCRIPTION
**Pull request by teto**
as mandated by https://github.com/neovim/neovim/pull/15259#issuecomment-934241413

### CODE REVIEW

**Comment by clason** [comment]
This will still run the `autoload#health` check, right? So you get duplicated output?

**Comment by teto** [comment]
don't merge as we decide on the way forward.

@clason it will so maybe we can tweak neovim directly to run just one of the healthchecks instead as you mentioned.

**Comment by justinmk** [comment]
why not delete `autoload#health` ? We would just need to wait until Nvim 0.5.2 is released.

**Comment by clason** [comment]
So the Lua healthcheck will be backported?

**Comment by justinmk** [comment]
> So the Lua healthcheck will be backported?

seems low risk, why not?

**Pull request merged**
