### PR TITLE
refactor(tests): simpler temp_dir detection

### PR DESCRIPTION
**Pull request by kylo252**
Tested on Windows and Linux (Arch).

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
This is not just a simplification but also changing the semantics of the code as it will now also utilize a `TEMP` environment variable on unix if available. Is that intended?

**Comment by kylo252** [comment]
> This is not just a simplification but also changing the semantics of the code as it will now also utilize a `TEMP` environment variable on unix if available. Is that intended?

I don't think that this variable is often used on unix, but even if it is, then it should be pointing to a `tmpfs` mount anyway. at least according to the search results I've found so far 😅

**Comment by mjlbach** [comment]
I'm fine with this

**Comment by kylo252** [comment]
FWIW, I just figured I can restore some minimalism after https://github.com/neovim/nvim-lspconfig/pull/1354

**Pull request merged**
