### PR TITLE
Use extracted vscode-json-languageserver

### PR DESCRIPTION
**Pull request by entropitor**

### CODE REVIEW

**Comment by mjlbach** [comment]
Why? We're already using https://github.com/hrsh7th/vscode-langservers-extracted which is more up to date.

**Review by justinmk — APPROVED** [review]

**Review by mjlbach — CHANGES_REQUESTED** [review]
see my comment asking for justification for the change

**Comment by entropitor** [comment]
Ah okay, from the name it looks like it was extracted out before microsoft extracted it out officially, but so the "fork" is still more up to date than the official extraction?

**Comment by mjlbach** [comment]
As far as I can tell, https://github.com/vscode-langservers is **not** in any way affiliated with microsoft (and probably shouldn't be using the vscode logo)

**Pull request closed without merging**
