### PR TITLE
Rename nvim_lsp to lspconfig

### LINKED ISSUE #97: rename to nvim-lspconfig
Probably should have anticipated this, but people are confused about nvim-lsp (this repo, not Nvim-builtin) vs vim.lsp (Nvim builtin). Although the nvim-lsp README.md makes it clear, it still confuses people in discussions ([example](https://www.reddit.com/r/neovim/comments/eq48cy/anyone_using_nvimlsp/)), and people who are just getting started.

So we should

- rename this repo to ~~nvim-lspconf~~ `nvim-lsp.configs`
- it also makes sense to rename the Lua module: it is confusing that `require'nvim_lsp'` is distinct from `vim.lsp`, since their names are semantically equivalent
    - see https://github.com/neovim/nvim-lsp/issues/97#issuecomment-583717327

I will do so in the next ~week if there are no objections.

cc @norcalli

### PR DESCRIPTION
**Pull request by h-michael**
resolve #97
related #334

This PR includes breaking changes as it involves changing the name of the module.
There is also a discussion in #334 about whether to remove the installer or stop using monorepo.
I think it's better to make these changes at the same time because multiple breaking changes in a short period of time can be confusing to users.

### CODE REVIEW

**Comment by justinmk** [comment]
LGTM

> This PR includes breaking changes as it involves changing the name of the module.

Let's define a `nvim_lsp` module that returns an error and/or `:echo` a message like `nvim_lsp` module was renamed to `lspconfig`.

**Comment by tjdevries** [comment]
I don't remember if we've talked about this before, but what about vim.lsp.config?

**Comment by justinmk** [comment]
> I don't remember if we've talked about this before, but what about vim.lsp.config?

But it isn't part of the `lsp` module. It's a separate extension.

Lots of variants were suggested in https://github.com/neovim/nvim-lspconfig/issues/97

**Comment by teto** [comment]
if we target a christmas release, may be good to proceed as early as possible, even if just for the rename (nvim_lsp to lspconfig)

**Comment by h-michael** [comment]
@tjdevries @teto 
Sorry for toooooo late replying. I've added a deprecated message.

**Review by teto — APPROVED** [review]

**Pull request merged**
