### PR TITLE
Gopls quickfix so it doesn't break if no go.mod or .git folder

### PR DESCRIPTION
**Pull request by pretentious7**
See title, in line with other lsp configs.

### CODE REVIEW

**Comment by pretentious7** [comment]
ah sorry about it sort of combining with the perlls pr, I can remove those commits if needed, but it'll probably take me a while to figure out and I did the stuff in the review, so is it ok?

**Comment by mjlbach** [comment]
I fixed the branch

**Comment by pretentious7** [comment]
thank you!

btw just for my reference, how did you do it? like what git commands?

**Comment by mjlbach** [comment]
`git rebase -i master`, then I deleted all non-pertinent commits (all but the last one) and force pushed once I checked the diff with your branch and master (I made some educated assumptions about your intentions with this PR :) )

**Comment by pretentious7** [comment]
I see. i need to learnt to use rebase and diff better. thanks!

**Comment by mjlbach** [comment]
Why did you close the PR?

**Comment by pretentious7** [comment]
...I don't understand how PR's work

**Comment by mjlbach** [comment]
Yes, when the PR is merged, the PR will close and the changes will be applied to the target branch (in this case master).

**Comment by mjlbach** [comment]
cwd is not a good fallback, sorry, cleaning up old PRs now

**Pull request closed without merging**
