### PR TITLE
Fix for vim.fs.find regression not returning parent directory

### LINKED ISSUE #3503: f675f broke ("refactor: deprecate util.find_package_json_ancestor")
### Description

Moving from https://github.com/neovim/nvim-lspconfig/commit/124be12d782d656b3c75b513a44d9e4728406078 to https://github.com/neovim/nvim-lspconfig/commit/f675f8c430ae3012f6d140899c2cec3b59e9cb43 breaks lspconfig for me

```                      
[lspconfig] unhandled error: ...al/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/util.lua:256: bad argument #1 to 'lines' (/Users/jrreed/dev/drg-maui-plugin/package.json/package.json: Not a directory)
```

I manually tested moving between both commits, works fine on previous commit

### PR DESCRIPTION
**Pull request by jacobrreed**
fixed #3503

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks. But this needs to be applied to all the cases in https://github.com/neovim/nvim-lspconfig/commit/f675f8c430ae3012f6d140899c2cec3b59e9cb43

**Comment by jacobrreed** [comment]
> Thanks. But this needs to be applied to all the cases in [f675f8c](https://github.com/neovim/nvim-lspconfig/commit/f675f8c430ae3012f6d140899c2cec3b59e9cb43)

right, dur, let me fix

**Comment by jacobrreed** [comment]
> Thanks. But this needs to be applied to all the cases in [f675f8c](https://github.com/neovim/nvim-lspconfig/commit/f675f8c430ae3012f6d140899c2cec3b59e9cb43)

fixed (i think 😄 )

**Comment by jacobrreed** [comment]
Changed fix commit label to be more appropriate

**Comment by folke** [comment]
This is causing havoc for a lot of users and I get a lot of bug reports...

Anything blocking for merging this?

All looks good to me. @justinmk?

I'll merge in half an hour or so unless someone tells me not to.

**Comment by folke** [comment]
Merged. ty!

**Comment by justinmk** [comment]
@folke fwiw, we will do more regular releases of this repo, e.g. I just tagged a new release: https://github.com/neovim/nvim-lspconfig/releases

It seems suboptimal that many consumers are following HEAD of this repo.

**Comment by folke** [comment]
@justinmk will change to follow versions in LazyVim.
I used to follow versions, but before there were no regular releases of lspconfig which lead to all sorts of issues.

**Pull request merged**
