### PR TITLE
feat: add steep support

### PR DESCRIPTION
**Pull request by okuramasafumi**
Steep is a static type checker for Ruby.

### CODE REVIEW

**Comment by mjlbach** [comment]
A configuration should return a table, not register itself into configs. Where did you see this style? We deprecated it awhile ago.

**Comment by okuramasafumi** [comment]
@mjlbach I copied it from https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md

**Comment by mjlbach** [comment]
Thanks for the catch, fixed the contributing documentation in https://github.com/neovim/nvim-lspconfig/commit/31be570201581dd23718722d51021dc55255454c

**Comment by okuramasafumi** [comment]
@mjlbach Thanks, so I force-pushed another commit which mimics `typeprof` config.

**Pull request merged**
