### PR TITLE
fix(dartls): explicitly pass the protocol to dartls

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/neovim/nvim-lspconfig/issues/1942
Works around upstream issue https://github.com/dart-lang/sdk/issues/49157

### CODE REVIEW

**Comment by christopherfujino** [comment]
Not sure why I'm getting a style lint on a file I didn't touch... https://github.com/neovim/nvim-lspconfig/runs/6715343306?check_suite_focus=true

**Comment by christopherfujino** [comment]
The parent of my commit is https://github.com/neovim/nvim-lspconfig/commit/c5dae15c0c94703a0565e8ba35a9f5cb96ca7b8a, which was merged 29 hours ago...

**Comment by christopherfujino** [comment]
However the PR was created in March, and apparently this check only runs pre-submit, not postsubmit? https://github.com/neovim/nvim-lspconfig/pull/1785

**Comment by lithammer** [comment]
The style lint error should be fixed by https://github.com/neovim/nvim-lspconfig/pull/1944. So if you rebase it will hopefully become green.

**Comment by christopherfujino** [comment]
> The style lint error should be fixed by #1944. So if you rebase it will hopefully become green.

Thanks! I pushed so it should be re-running...

**Comment by christopherfujino** [comment]
One more try to fix lint-commits: https://github.com/neovim/nvim-lspconfig/runs/6716423723?check_suite_focus=true

**Pull request merged**
