### PR TITLE
Run lint job as sudo to make CI pass again

### PR DESCRIPTION
**Pull request by theHamsta**
At least 2 of 3

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks. Looks like CI is ok though now?

**Comment by justinmk** [comment]
weird, seems like CI is having a problem again

**Comment by theHamsta** [comment]
The problem on macos seems to be that Cmake gets installed twice. Maybe just remove int from the brew install command?

**Comment by theHamsta** [comment]
Strange: even though all the checks passed. They get only executed before the docgen commit. Maybe an additional trigger for the workflows is necessary now?

**Comment by justinmk** [comment]
Thanks, this is helpful!

Side note: do we really actually need a macos build for this repo? Seems overwrought.

**Pull request merged**
