### PR TITLE
Add extension to pyright command name on Windows

### PR DESCRIPTION
**Pull request by benawas**
Same as  #406, but for pyright

### CODE REVIEW

**Comment by h-michael** [comment]
@benawas 
This change not only changed the ".cmd" for Windows, but also changed the value of "binaries" on all OS.

**Comment by igrep** [comment]
@h-michael Watch the patch again! It replaces the extension only if `vim.fn.has('win32') == 1`, like https://github.com/neovim/nvim-lspconfig/pull/298/files, and my https://github.com/neovim/nvim-lspconfig/pull/406/files.

**Comment by h-michael** [comment]
@igrep No. This commit also changes binaries value from `pyright` to `pyright-langserver`.

**Comment by lithammer** [comment]
> @igrep No. This commit also changes binaries value from `pyright` to `pyright-langserver`.

To me it actually looks more correct now since the binary is called `pyright-langserver`, not `pyright`.

**Comment by h-michael** [comment]
I understood the difference between pyright and pytight-langserver.
So pyright is a CLI and pytight-langserver is a language server.
https://github.com/microsoft/pyright/blob/a0620921898dfc5c0ecc704d53dbea3f6b2857e6/packages/pyright-internal/src/server.ts
https://github.com/microsoft/pyright/blob/f8db95da805d1944c605494193691ab062c3ee7b/packages/pyright-internal/src/pyright.ts

**Review by h-michael — APPROVED** [review]

**Comment by lithammer** [comment]
pyright is also what the npm package is called, you can't _just_ install pyright-langserver.

**Pull request merged**
