### PR TITLE
jdtls: Add workaround for textDocument version of 0

### PR DESCRIPTION
**Pull request by dradtke**
See https://github.com/eclipse/eclipse.jdt.ls/issues/1695

### CODE REVIEW

**Comment by mjlbach** [comment]
Can you squash? 

Also @mfussenger I defer to you on this as the resident jdtls expert 😆

**Comment by mfussenegger** [comment]
Looks okay to me.

To be complete it would also require a workaround for the rename operation, otherwise that will have the same problem.
Here's how it's done in nvim-jdtls: https://github.com/mfussenegger/nvim-jdtls/commit/ca5154f57df45230a3c4aa3b67cc49c516299edf

**Comment by dradtke** [comment]
@mjlbach / @mfussenegger Just squashed and cleaned it up a bit.

**Comment by mjlbach** [comment]
Thanks for your contribution! Please ping me if jdtls ever fixes this 😆

**Pull request merged**
