### PR TITLE
feat: allow `:LspStop` and `:LspRestart` commands to apply to current buffer clients

### LINKED ISSUE #1781: Apply `:LspStop` and `:LspRestart` to current buffer only
### Language server

_No response_

### Requested feature

Currently, `:LspStop` and `:LspRestart` require knowing the specific ID of a client, or running them without arguments applies to *all* clients. It seems more likely that you would want these commands to only apply to the current buffer. We could do this either by creating buffer-specific commands (e.g. `:LspBufStop` or `:LspBufRestart`) or using the argument `0` to indicate the current buffer (as client indexing starts with `1`).

### Other clients which have this feature

_No response_

### PR DESCRIPTION
**Pull request by rish987**
This makes the argument `0` mean to stop or restart all clients for the current buffer, which is useful since it would seem common to want to restrict these commands to a certain buffer, but you rarely know what the specific IDs of the clients are.

Closes #1781.

### CODE REVIEW

**Comment by mg979** [comment]
I opened a PR to fix this at #1808. Your PR doesn't really solve the main problem (`LspStop` without arguments stops everything on all buffers, but `LspStart` cannot restart all clients on all buffers, only on current buffer). So `LspStop` shouldn't stop all clients in any circumstance.

**Comment by rish987** [comment]
SGTM, if it's described as such in the readme we should probably go with that. I have no issues either way though.

**Comment by mjlbach** [comment]
I don't personally care if we also change the documentation. I never use these commands, so if we want to change their meaning that is fine by me. IMO `:LspStop` completely shutting down all language servers and disabling the autocommands is probably what I would expect, and `:LspStop 0` limiting it to the current buffer is what I would prefer.

**Comment by mg979** [comment]
> IMO :LspStop completely shutting down all language servers and disabling the autocommands is probably what I would expect

`LspStart` restarts the clients only in the current buffer. This means that after `LspStop` you should restart each client individually. As they are the commands are useless.

> I never use these commands

Yeah. Some people would like to use them though, and they are not usable right now. Stopping all clients and restarting them all every time would be (imho) overkill, unnecessary and potentially very taxing for no gain. Personally I use LspStop to pause the clients if it misbehaves or if diagnostics annoy me.

If there is the need for some `LspStopAll`, `LspRestartAll` they should be different commands, imho. I don't see the point in stopping all clients in all buffers and restarting them every now and then. That's not what I'd normally want these commands for, so I don't know why you think that stopping all clients on all would be better. I guess it's because, as you said, you don't use these commands.

**Comment by mg979** [comment]
An easy alternative for `LspStop` would be to have
```
:LspStop                     stop all clients in current buffer
:LspStop {id}                stop client with id
:LspStop!                   stop all clients on all buffers
```

But the problem with `LspStart` would remain, stopping all clients on all buffers seems a last resort to me.

**Comment by rish987** [comment]
(Sorry, I'm ramping up at a new job but will get back to this soon. This PR isn't exactly what I think we want yet, and I do like the idea above about the different `:LspStop` variants.)

**Comment by rish987** [comment]
Okay, sorry for the long wait, this is ready for review now! @mg979 I made it work according to your suggestion, let me know what you think!

**Comment by rish987** [comment]
cc @lithammer @justinmk

**Comment by glepnir** [comment]
@rish987  this pr will conflict with #1984

**Comment by justinmk** [comment]
These commands are intended as a high-level interface. If you want to have fine-grained behavior, use `vim.lsp.stop_client()`.

**Pull request closed without merging**
