### PR TITLE
fix: textlsp docs table at wrong position

### PR DESCRIPTION
**Pull request by hangyav**

### CODE REVIEW

**Comment by glepnir** [comment]
can you squash and rebase

**Comment by hangyav** [comment]
Sure, but since I'm not an expert could you please help me figure out which ones should I squash? Only last 2 commits or all 4 (since [08b827d](https://github.com/neovim/nvim-lspconfig/pull/2469/commits/08b827d1e7d07a787ece8d7b0fda6559f438e734) was already merged)? Thanks!

**Comment by glepnir** [comment]
i can squash merge.

**Comment by hangyav** [comment]
thanks a lot!

**Pull request merged**
