### PR TITLE
Add option to disable autostart

### LINKED ISSUE #691: ability to disable autostart
I would like to decouple the configuration of the language server and its autostart so that I can configure my LSPs globally but decide on a per project basis whether to launch the server or not (via .nvimrc for instance)

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #691 

@teto The idea is to make an autocommand based on the root directory which invokes a wrapper around try_add that subsequently checks filetype.

1. Disable autostart when you configure your language server
```lua
local sumneko_cmd
if vim.fn.executable("lua-language-server") == 1 then
  sumneko_cmd = {"lua-language-server"}
else
  local sumneko_root_path = vim.fn.getenv("HOME").."/.local/bin/sumneko_lua"
  sumneko_cmd = {sumneko_root_path.."/bin/macOS/lua-language-server", "-E", sumneko_root_path.."/main.lua" }
end

nvim_lsp.sumneko_lua.setup {
  cmd = sumneko_cmd;
  autostart = false; -- This is the important new option
  on_attach = on_attach,
  capabilities = capabilities;
  settings = {
      Lua = {
          runtime = {
              -- Tell the language server which version of Lua you're using (LuaJIT in the case of Neovim)
              version = 'LuaJIT',
              -- Setup your lua path
              path = vim.split(package.path, ';'),
          },
          diagnostics = {
              -- Get the language server to recognize the `vim` global
              globals = {'vim'},
          },
          workspace = {
              -- Make the server aware of Neovim runtime files
              library = {
                  [vim.fn.expand('$VIMRUNTIME/lua')] = true,
                  [vim.fn.expand('$VIMRUNTIME/lua/vim/lsp')] = true,
              },
          },
      },
  },
}
```
2. `:lua require('lspconfig').sumneko_lua.launch()` To activate the server (and subsequent autolaunch for buffers opened within this root) for the given root directory

### CODE REVIEW

**Comment by mjlbach** [comment]
I guess it would be nice to have every buffer "just work" without triggering the autocmd, but I'm not sure the best thing to do for this.

**Comment by teto** [comment]
thanks I will give it a spin. the addition of a launch command is appreciated.

**Comment by teto** [comment]
thanks that works. I am a bit wary of `launch` that could be confusing with `start` ?

**Comment by mjlbach** [comment]
I'm not sure what else to call it, it does a bit more than start since it watches for additional buffers within the workspace. Name suggestions welcome for sure

**Comment by dbalatero** [comment]
@mjlbach I tested it and it worked for my restart case fyi!

**Pull request merged**
