### PR TITLE
Feature/zk

### PR DESCRIPTION
**Pull request by wurosh**
#1222 but properly rebased

### CODE REVIEW

**Comment by mjlbach** [comment]
@wurosh how exactly are you using zk.new and init?

**Comment by wurosh** [comment]
`zk.index` updates the internal database to match what's on disk when you do some things manually (such as create a file the old-fashioned way). `zk.new` is a way for you to create a new note and let zk handle all the nasty stuff like hashes and respecting naming conventions you set up in your `config.toml`. Personally, I wrap it in a utility function that does so based on the link at point, but I didn't add that here because:
1. Some people use the built-in markdown plugin
2. Some people use `plasticboy/vim-markdown`
3. Some use wiki links instead of markdown links
4. Some people use a different format altogether

**Comment by mjlbach** [comment]
Thanks! My question was more why you set the references to the functions as entries in the config table rather than using our commands interface (I'm doing a big refactor of configs and this stuck out to me)

**Comment by wurosh** [comment]
I wasn't aware of the commands interface but I'm happy to do a refactor. Any good examples to look at?

**Pull request merged**
