### PR TITLE
fix: update luarocks-tag-release action + set license

### PR DESCRIPTION
**Pull request by mrcjkb**
@teto this version escapes quotes in the description: (https://github.com/neovim/nvim-lspconfig/pull/2430#issuecomment-1418286733)

I also added a license field, because GitHub doesn't seem to recognize it.

### CODE REVIEW

**Comment by teto** [comment]
Let's try it again :D

**Comment by mrcjkb** [comment]
Looks like it worked. But the `license` input isn't yet supported...

**Comment by teto** [comment]
I've force pushed the same tag (I was kinda expecting it to fail actually ^^'') maybe that's why ? you are thinking about this for the licence ? https://github.com/neovim/nvim-lspconfig/actions/runs/4098948656/jobs/7068421136#step:4:395  
I know the labels are not automatically picked up from the rockspec either (what a shame) so it's possible the license has to be set from the frontend too.

**Comment by mrcjkb** [comment]
> I know the labels are not automatically picked up from the rockspec either (what a shame) so it's possible the license has to be set from the frontend too.

LuaRocks picks up the license from the rockspec. But the `luarocks-tag-release` action tries to generate the rockspec using the license fetched from the GitHub API. And it seems like GitHub can't tell what license nvim-lspconfig has.

image

**Comment by justinmk** [comment]
What steps (if any) does a human need to take to create a release for nvim-lspconfig? Would be good to document those in e.g. readme.md, even if it's just:

1. create a tag
2. the [release action](https://github.com/neovim/nvim-lspconfig/actions/workflows/release.yml) does the rest

**Comment by mrcjkb** [comment]
> What steps (if any) does a human need to take to create a release for nvim-lspconfig? Would be good to document those in e.g. readme.md, even if it's just:
> 
> 1. create a tag
> 2. the [release action](https://github.com/neovim/nvim-lspconfig/actions/workflows/release.yml) does the rest

Here's a PR with some notes: https://github.com/neovim/nvim-lspconfig/pull/2690/files

**Comment by justinmk** [comment]
GHA reports a warning:

    Unexpected input(s) 'licence', valid inputs are ['name', 'version', 'specrev', 'dependencies', 'test_dependencies', 'labels', 'copy_directories', 'summary', 'detailed_description', 'template', 'license', 'extra_luarocks_args', 'fail_on_duplicate']

**Pull request merged**
