### PR TITLE
fix(npm): resolve the command correctly on windows

### LINKED ISSUE #1500: Full windows support for all applicable servers
### Description

I want to delete [this section](https://github.com/neovim/nvim-lspconfig#windows) from the readme. So lets test all the language servers on windows and update the cmd [like this](https://github.com/neovim/nvim-lspconfig/blob/8c9962bae5ac3b1f8b3d84c18314325f2d8df7fd/lua/lspconfig/server_configurations/pyright.lua#L3-L6)

Please list servers that need to be updated (better yet file PRs)

### PR DESCRIPTION
**Pull request by kylo252**
Fixes #1500

### CODE REVIEW

**Comment by kylo252** [comment]
If it turns out that there's a way to handle this in core without invoking `cmd.exe`, then all we have to do is `dap` that `win32` condition and done :)

**Comment by lithammer** [comment]
Is this only Node specific, or could we blanket apply this to every `cmd` in a more central location (instead of every server config file)?

**Comment by kylo252** [comment]
> Is this only Node specific, or could we blanket apply this to every `cmd` in a more central location (instead of every server config file)?

It's probably node-specific, since it depends on creating [shims](https://www.npmjs.com/package/cmd-shim). We can add handling for that either globally or in core, but it's going to take more effort.

**Comment by kylo252** [comment]
@williamboman, here's my attempt to describe the problem more clearly https://github.com/neovim/neovim/issues/16484

**Comment by mjlbach** [comment]
@williamboman this solves the issue of volta, which does not provide the postfixed `.cmd` scripts. It should universally work on windows. I'd rather not inject some modification of the `cmd` passed to start_client to account for windows but fix it locally in lspconfig per server.

**Comment by kylo252** [comment]
We can also prepend the logic once in the command that's sent to `start_client`. It's _probably_ fine :sweat_smile:

**Comment by mjlbach** [comment]
> We can also prepend the logic once in the command that's sent to start_client.

I am saying no 🙃

**Comment by williamboman** [comment]
What do you think of having a set of candidates that will be attempted instead? Like

```lua
local candidates = {
  { "typescript-language-server" },
  is_win and { "typescript-language-server.cmd" },
  is_win and { "cmd.exe", "/C", "typescript-language-server" }
}

return {
  default_config = {
    cmd_candidates = candidates
  }
}
```

**Comment by mjlbach** [comment]
No

**Comment by kylo252** [comment]
For completeness' sake, there's also this ~~atrocity~~ thing which seems like a core dependency for `npm` and has about 1.7M weekly downloads......

> Figure out what a `cmd-shim` is pointing at. This acts as the equivalent of `fs.readlink`.
https://github.com/npm/read-cmd-shim/blob/488b31e867b2f7df6eb44fca6569a5771ee03aee/index.js#L1-L69

**Comment by mjlbach** [comment]
I don't understand why this PR is not sufficient to solve the issue. I think having a chain of cmd is hacky at best. There is no good way to test ahead of time which is executable and I like the simplicity of configurations being *light* sugar over uv_spawn

**Comment by williamboman** [comment]
> I don't understand why this PR is not sufficient to solve the issue. I think having a chain of cmd is hacky at best. There is no good way to test ahead of time which is executable and I like the simplicity of configurations being _light_ sugar over uv_spawn

I'm not opposed to it! I just wanted to raise concerns around using `cmd.exe` as an intermediary. Are signals and pipes properly forwarded, are there any throughput bottlenecks? 🤷‍♂️ One thing I've learned, and especially for Windows, is that things never work in a reliable manner, so this will probably produce a new set of issues haha. We'll see

**Comment by kylo252** [comment]
I should probably add those managed by `yarn` as well.

**Review by kylo252 — COMMENTED** [review]
@mjlbach, what about these two: 

- https://github.com/neovim/nvim-lspconfig/blob/5b8624c1bcd332e9fd7ae33a2ca910adb31a7ae7/lua/lspconfig/server_configurations/theme_check.lua#L7
- https://github.com/neovim/nvim-lspconfig/blob/5b8624c1bcd332e9fd7ae33a2ca910adb31a7ae7/lua/lspconfig/server_configurations/rescriptls.lua#L24

Do they count?

**Comment by mjlbach** [comment]
I don't think so

**Comment by kylo252** [comment]
I should probably test the ruby ones, ~~but I have no idea if that's even supported on Windows...~~ It is, and it's the same issue as `npm`.

I should add the same fix for all the `gem` managed servers as well 😢

**Comment by mjlbach** [comment]
Out of date installation instructions can be handled in a separate PR

**Comment by kylo252** [comment]
There are probably a few more node modules, but I'd have to use my old script from https://github.com/neovim/nvim-lspconfig/pull/1254 to find them, since they're missing the installation instructions which I've been using so far to classify them.

**Comment by williamboman** [comment]
Sorry for interjecting, but wasn't this only a problem with Volta on Windows (i.e. only Node.js)?

**Comment by mjlbach** [comment]
Well, some of the cmd were missing too, and it seems like this is a universal fix.

**Comment by kylo252** [comment]
I think that should be it! There's still `typeroft`, but it requires ruby 3.1 which didn't get installed by default for me 🤷  https://github.com/neovim/nvim-lspconfig/blob/5b8624c1bcd332e9fd7ae33a2ca910adb31a7ae7/lua/lspconfig/server_configurations/typeprof.lua#L13

**Comment by mjlbach** [comment]
Awesome, thanks for the hard work!

**Comment by mjlbach** [comment]
Also remove the section from readme.md on windows support.

**Comment by kylo252** [comment]
> add a section in CONTRIBUTING.md explaining this.

I'm not very good at writing these kinds of docs, please let me know if you had something else in mind. Maybe @clason can take a look as well.

**Comment by mjlbach** [comment]
I'm going to go ahead and merge this. If there are issues it can be reverted.

**Pull request merged**
