### PR TITLE
chore: update dcmls config

### PR DESCRIPTION
**Pull request by RobertBrunhage**

### CODE REVIEW

**Comment by glepnir** [comment]
It's better test in your local to make sure all it can works . and add more spec in default description about  why add yaml filetype .

**Comment by RobertBrunhage** [comment]
> It's better test in your local to make sure all it can works.
Got feedback from creator of `DCM` that `--` was missing. Was not visible locally.

> and add more spec in default description about why add yaml filetype 
It can analyze yaml files as well for lint rules etc.

**Comment by glepnir** [comment]
emm I think it's better disable yaml as  default.. because yaml has their own server ymls.

**Comment by RobertBrunhage** [comment]
> emm I think it's better disable yaml as default.. because yaml has their own server ymls.

Got it, will do

**Pull request merged**
