### PR TITLE
refactor!: replace util.path.join with vim.fs.joinpath

### PR DESCRIPTION
**Pull request by dundargoc**
We should rely on builtin functionality if possible to minimize code duplication.

### CODE REVIEW

**Comment by dundargoc** [comment]
Unsure what general strategy is for removing lspconfig functions. This seems used fairly frequently: https://github.com/search?q=util.path.join+language%3ALua&type=code. Worth deprecating, or do we just go for it?

**Comment by justinmk** [comment]
> what general strategy is for removing lspconfig functions

we should keep the util stuff around to avoid breaking downstream. meanwhile, in this repo:

- CI should fail if any config uses a deprecated `util` function
- we should remove all docs that suggest a deprecated `util` function

**Comment by justinmk** [comment]
To be clear, my above comment is in favor of this PR. When you asked about "removing lspconfig functions" I interpreted that to mean removing the `util.xx` entirely

**Comment by justinmk** [comment]
OTOH https://github.com/neovim/nvim-lspconfig/issues/3342 is making me think that 0.9 support is still worthwhile, if it doesn't add too much burden.

**Pull request closed without merging**
