### PR TITLE
chore: use `loop.os_uname()` instead of `fn.has'win32'`

### PR DESCRIPTION
**Pull request by numToStr**
Added `util.is_windows` and replaced all the occurrences of `vim.fn.has 'win32' == 1` with the same.

### CODE REVIEW

**Comment by numToStr** [comment]
Huh...CI is failing bcz npm can't install package 🤦🏼‍♂️

**Comment by glepnir** [comment]
you format all markdown file ? please do not , Honestly it's no improvement. are almost the same .

**Comment by numToStr** [comment]
> you format all markdown file ? please do not , Honestly it's no improvement. are almost the same .

prettier auto formatted it. I'll revert it.

**Comment by numToStr** [comment]
CI is happy 🎉

**Comment by glepnir** [comment]
`is_windows` not in util table. you can' do this. and server configuration is independent. should not be associated with `util`

**Comment by numToStr** [comment]
> you can' do this. and server configuration is independent. should not be associated with util

Why not? It just a boolean, its not associating anything IMO. Configurations are still independent.

**Comment by glepnir** [comment]
`is_windows` not in `util` table it's not a export variable. 

By independent I mean it doesn't apply to anything in other files. lspconfig is just a temporary plugin that provides some basic server configuration. Please don't treat it as a complete plugin. Check out the roadmap for the purpose of the project

**Comment by numToStr** [comment]
We can mark it private for public use. This shouldn't prevent `util` to be used internally otherwise we'll end up repeating the common task (one that this PR solves).

And, I know what's the goal of lspconfig :)

**Comment by glepnir** [comment]
In my opinion no need.

**Comment by numToStr** [comment]
Well then you can close this :)

**Pull request closed without merging**
