### PR TITLE
modify ltex server config

### PR DESCRIPTION
**Pull request by flaviusbuffon**
When using ltex as latex lsp server, it will notice that no root_dir,  I change somethings in ltex.lua

### CODE REVIEW

**Comment by mjlbach** [comment]
@clason I feel like we had discussed this and I remember there being a reason not to do this, but I can't recall what it was.

**Comment by clason** [comment]
I think the argument was that `ltex` is in fact _not_ a LaTeX lsp server (although `tex` is one of several filetypes it works well for), so hardcoding this as *primus inter pares* doesn't seem appropriate.

**Comment by clason** [comment]
The right thing here is to check whether `ltex-ls` works with `single_file_support = true`, and if so, add that to the default settings.

**Comment by mjlbach** [comment]
it should AFAIK

**Comment by mjlbach** [comment]
I think this addresses your main concern https://github.com/neovim/nvim-lspconfig/pull/1556

**Pull request closed without merging**
