### PR TITLE
Add Crystalline (Crystal)

### PR DESCRIPTION
**Pull request by gwerbin**
Adds the [Crystalline](https://github.com/elbywan/crystalline) language server for Crystal, a successor to Scry.

### CODE REVIEW

**Comment by lithammer** [comment]
CONFIG.md is automatically generated. So remove those changes.

**Comment by lithammer** [comment]
Ping @gwerbin

**Comment by gwerbin** [comment]
Done @lithammer, thanks for the reminder!

**Comment by lithammer** [comment]
Can you squash the commits as well? I'll merge after.

**Comment by gwerbin** [comment]
Done @lithammer

**Comment by lithammer** [comment]
Thanks!

**Pull request merged**
