### PR TITLE
Add serve-d

### PR DESCRIPTION
**Pull request by CodeLongAndProsper90**
This adds support for github.com/Pure-D/serve-d, a Dlang language server

### CODE REVIEW

**Comment by ljmf00** [comment]
Sorry for ping @mjlbach, but can you review this simple PR? I already tested and it is working fine. The only change I would make is giving a better description on the `docs` field.

**Comment by mjlbach** [comment]
Style lint is failing, and I would prefer more explicit installation instructions.

**Comment by mjlbach** [comment]
You'll need to fix the rebase

**Comment by CodeLongAndProsper90** [comment]
Ah, it seems I messed this up. I'll close this PR and open a new one that should, hopefully, not format thing erratically.

**Comment by ljmf00** [comment]
You just need to rebase instead of merge :wink:

**Comment by CodeLongAndProsper90** [comment]
Well I've lost the fork (:roll_eyes:) so I've made a new one at #1080

**Pull request closed without merging**
