### PR TITLE
fix(command): check server exist in configs

### PR DESCRIPTION
**Pull request by glepnir**

### CODE REVIEW

**Comment by glepnir** [comment]
@wojciech-kulik  could you check this.

**Comment by wojciech-kulik** [comment]
There is no error now, but the LSP is not attached again.

**Comment by wojciech-kulik** [comment]
Now it works for my regular LSP, but for copilot it prints tons of:
image

I have to restart nvim then

**Comment by glepnir** [comment]
copilot not in lspconfig

**Comment by wojciech-kulik** [comment]
Maybe copilot is some special case. Because it doesn't appear on Configured servers list:  from :LspInfo

I'm using the official plugin: `github/copilot.vim`

**Comment by glepnir** [comment]
@wojciech-kulik fixed. but notice the copilot will not restart because it not exist in lspconfig. you must need do some wrap

**Comment by wojciech-kulik** [comment]
Makes sense! Now I checked and everything works fine on both Neovim versions! Thank you 🍻

**Pull request merged**
