### PR TITLE
feat(ui): lspinfo: better layout

### PR DESCRIPTION
**Pull request by kylo252**
# Description
 
Various improvements to LspInfo 

- Allow better readability by applying some extra paddings and a border
- Remove redundant information, e.g. if a client is attached then it's already active so no need to display the full info about it multiple times
- Break-out the arguments part of the client command
- Refactor LspInfo and extract some utility functions to allow for better maintainability

This also means we now have more available space to display any other useful information.

### before
image

### after
image

### CODE REVIEW

**Comment by justinmk** [comment]
nice improvement, thanks!

side note: weird that lspconfig has a ui/ subsystem, that is rather an overreach for a "bunch of configurations".

**Comment by gegoune** [comment]
Not everyone like borders, Justin really has a good point, so I assume it will never become configurable?

**Comment by clason** [comment]
bad bot

**Comment by clason** [comment]
The end goal is for lspconfig to indeed be nothing but configs. The info should be upstreamed and folded into `:checkhealth` as part of this.

(Which is getting unwieldy; putting efforts into structuring it better would be welcome.)

**Comment by mjlbach** [comment]
I just woke up. I'm not happy this was merged. 

* The title is redundant and wastes vertical space
* It doesn't make sense to split cmd/args, this is an arbitrary distinction
* The point of listing active client IDs, is it's important for users to know which particular client is attached to a buffer, and the particular active root directories associated with each client. This is critical for debugging, especially in the case the root directories do not match. Also many operations (get_client_by_id, for example) rely on the specific client ID attached to the current buffer.
* The padding is ridiculously large
* Why are we adding rounded borders by default? This looks awful with the gap
* The code was originally extracted from popup.nvim so the providence is correct

**Comment by mjlbach** [comment]
You can file a new PR and I'll review it.

**Comment by kylo252** [comment]
> * It doesn't make sense to split cmd/args, this is an arbitrary distinction (we don't have the notion of args in a setting, so people will ask "Where is args defined? Should I add this in setup?" People will copy/paste this onto the command line to reproduce launching the language server. Before it was pretty easy to yank onto the command line.

I understand this point, but which is more common: 
1. get an overview of the flags that are passed to the server
2. get the literal command that you can copy paste somewhere else

We don't necessarily need to add the "args" distinction, it is more about printing them in a table form, _even though I didn't do the last part._

> * The point of listing active client IDs, is it's important for users to know which particular client is attached to a buffer, and the particular active root directories associated with each client. This is critical for debugging, especially in the case the root directories do not match. Also many operations (get_client_by_id, for example) rely on the specific client ID attached to the current buffer.

I'm not sure I did anything to contradict this? I kept the full listing of the active clients and removed the other ones **when they're duplicated**. I'll add a few more screenshots in the new PR.

**Comment by dhruvmanila** [comment]
> Not everyone likes borders, Justin really has a good point, so I assume it will never become configurable?

You can update the window configuration in a `ftplugin` file. So, in `{after}/ftplugin/lspinfo.lua`:
```lua
vim.api.nvim_win_set_config(vim.api.nvim_get_current_win(), { border = "single" })
```

**Comment by mjlbach** [comment]
> I understand this point, but which is more common:

    get an overview of the flags that are passed to the server
    get the literal command that you can copy paste somewhere else

The latter, as it's explicitly recommended as a debugging step in the lspconfig readme which I also wrote :) 

> I'm not sure I did anything to contradict this? I kept the full listing of the active clients and removed the other ones when they're duplicated. I'll add a few more screenshots in the new PR.

Add the client IDs next to the printed server name in the first section and you're good.

**Pull request merged**
