### PR TITLE
refactor: replace deprecated vim.loop with vim.uv

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by glepnir** [comment]
If don't plan to continue supporting 0.9 now, that's fine,

**Comment by dundargoc** [comment]
> Requires Nvim 0.10 above. Update Nvim and nvim-lspconfig before reporting an issue.

I just went with what the README says.

**Comment by glepnir** [comment]
oh i see .. it has been updated . let's go.

**Review by glepnir — APPROVED** [review]

**Comment by justinmk** [comment]
Do we need to add a has('nvim-0.10') check which shows a message?

**Comment by glepnir** [comment]
Since  updated the description of minimum requirements in the doc, may need add a version check in plugin/lspconfig.lua and ask for an upgrade

**Comment by dundargoc** [comment]
> Do we need to add a has('nvim-0.10') check which shows a message?

https://github.com/neovim/nvim-lspconfig/pull/3338

**Pull request merged**
