### PR TITLE
Add GraphQL Language Service

### PR DESCRIPTION
**Pull request by JoosepAlviste**

### CODE REVIEW

**Comment by mjlbach** [comment]
LGTM, thanks for the PR. Assume you've tested and everything works?

**Comment by JoosepAlviste** [comment]
@mjlbach Hey! Yep, it works for me if a GraphQL config file exists in the project.

I didn't add the GraphQL config instructions to the docs though. Hopefully, the `graphql-language-service` docs cover it well enough.

**Comment by yassinebridi** [comment]
Hey @JoosepAlviste would you mind sharing how you tested that, i'm trying to add a language server, and used your example as a blueprint. i tried adding the `graphql` file to the `lua` folder of my local `nvim-lspconfig` plugin.

**Comment by JoosepAlviste** [comment]
@yassinebridi Sure, here's how I did it:

1. Create a new folder
2. Add a `.graphqlrc` file inside (this file is used as the root marker) with the contents:

```yml
schema: https://countries.trevorblades.com/
documents: ./*.graphql
```

(https://countries.trevorblades.com/ is a free to use GraphQL API)

3. Create a new `test.graphql` file inside the folder with the contents:

```graphql
query test {
  continents {
    code
    foobar
  }
}
```

4. The `foobar` field should be marked with an error (this field doesn't exist in the GraphQL schema)
5. Try to play around with the file (trigger autocompletion, etc.)

I don't know much about the language server itself, but this simple test seems to work for me.

**Comment by JoosepAlviste** [comment]
Hey @mjlbach, is this PR OK to be merged? Or is there anything I can do to improve it?

**Comment by mjlbach** [comment]
Merged

In the future, package.json does not refer to the generic package.json for the module, but rather the one that defines the settings that can be sent to the language server (bad naming convention I guess), it's not a mandatory part of a config, but it just handles autodocgen (which the package.json in this PR broke). I pushed a fix.

**Pull request merged**
