### PR TITLE
bug: default_config was overwritten

### PR DESCRIPTION
**Pull request by mnowotnik**
#848

### CODE REVIEW

**Comment by mjlbach** [comment]
It's not. This is in the documentation section of the table.

**Comment by mnowotnik** [comment]
It is. Debug it or just check the source code.
Screenshot_20210417-190758_Chrome

**Comment by mjlbach** [comment]
I can promise you it's not, if you delete lines 17 to 71, you'll see default_config is a child of docs, it's 100% not overwritten.

**Comment by mnowotnik** [comment]
You're right. For a second there, I got a little paranoid I'm leaking telemetry. 
Sorry for inconvenience.

**Pull request closed without merging**
