### PR TITLE
feat(ts_ls)!: rename `tsserver` to `ts_ls`

### PR DESCRIPTION
**Pull request by ofseed**
`tsserver` cannot be used as an abbreviation for `typescript-language-server`, because there is [`tsserver`](https://github.com/microsoft/TypeScript/wiki/Standalone-Server-(tsserver)) already and it is completely different from `typescript-language-server`. This is misleading.

As the [README of `typescript-language-server`](https://github.com/typescript-language-server/typescript-language-server/blob/master/README.md) says, it's a wrapper of `tsserver`. This abuse has been around for so many time in lspconfig that people don't realize they are two different things, and are then confused by replacements of `typescript-language-server` like [typescript-tools.nvim](https://github.com/pmizio/typescript-tools.nvim) and [vtsls](https://github.com/yioneko/vtsls).

### CODE REVIEW

**Comment by ofseed** [comment]
Now the `server_configuration.md` is generated, not manually edited.

**Comment by ofseed** [comment]
@glepnir Could you please review it?

**Comment by glepnir** [comment]
https://github.com/search?q=lspconfig.tsserver&type=code

quick search it has 5.6k  files.. so  hasty merge will only result in a lot of complaints.  best approach is to popup a notify and keep it available and remove it in the next release.

**Comment by ofseed** [comment]
> best approach is to popup a notify and keep it available and remove it in the next release.

It does, you can see in [there](https://github.com/ofseed/nvim-lspconfig/blob/7345e004eaf0bda621df39322c5fa32aaf53e975/lua/lspconfig.lua#L30-L33), the snippet redirects `tsserver` to `ts_ls` and notify `tsserver` is outdated, will not break users' configuration brutally.

But considering your search result, I will do extra PR for `mason.nvim` and `mason-lspconfig.nvim`, and then we can merge them as much as possible at the same time so that most of the users who use mason will not be affected. I will let you know when my PR for mason and mason-lspconfig is ready.

**Comment by polyzen** [comment]
Could just wait for https://github.com/microsoft/TypeScript/issues/39459 to be resolved and then do something about it then.

**Comment by ofseed** [comment]
@polyzen  Not that related. There are two points I want to emphasize.

1. Changing the name will not break users' configurations, `lspconfig.tsserver.setup{}` is still valid and will only have a warning that `tsserver` is deprecated suggest using `ts_ls` instead. In fact, we've already done that for `lua_ls`, formerly called `sumneko_lua`, which I think most neovim users will setup no matter what language they are mainly writing. The breaking change should not be that painful.

2. One of the reasons for creating this PR is to prepare the issue you linked to be resolved. If we do not merge this PR and then merge it after the real `tsserver` implements LSP, the name `tsserver` will refer to a different thing after that. That is, `tsserver` in lspconfig is formerly to be `typescript-language-server`, but then be the real `tsserver`. This will cause the meaning of `lspconfig.tsserver.setup` changed silently, and users' configurations will setup the real `tsserver`, not `typescript-language-server`. It should be very difficult for users to find out what happened.

**Comment by glepnir** [comment]
seems like lsp-mode also use ts_ls.. but I'm wondering if this abbreviation is appropriate. How about typescript_ls? ts is a bit ambiguous.

**Comment by justinmk** [comment]
Well reasoned. Thank you

**Comment by SannanOfficial** [comment]
So, umm guys, I now get "tsserver is deprecated, use ts_ls instead" in my neovim now. How can I fix this? Do I need to edit some config file and change the name to ts_ls or what? I am asking this because mason doesn't have a separate ts_ls option to install within it.

**Comment by ic-768** [comment]
> So, umm guys, I now get "tsserver is deprecated, use ts_ls instead" in my neovim after updating. How can I fix this? Do I need to edit some config file and change the name to ts_ls or what? I am asking this because mason doesn't have a separate ts_ls option to install within it.

I was also blindsided by this. Here's what I did

```
	{
		"williamboman/mason.nvim",
		dependencies = {
			"williamboman/mason-lspconfig.nvim",
			"neovim/nvim-lspconfig",
			"hrsh7th/nvim-cmp",
		},
		config = function()
			require("mason").setup()
			require("mason-lspconfig").setup({
				ensure_installed = {
					"lua_ls",
					"pyright",
					"ruff_lsp",
					"tsserver",
					"eslint",
					"tailwindcss",
					"emmet_language_server",
					"jsonls",
				},
			})

			require("mason-lspconfig").setup()

			-- automatically install ensure_installed servers
			require("mason-lspconfig").setup_handlers({
				-- Will be called for each installed server that doesn't have
				-- a dedicated handler.
				--
				function(server_name) -- default handler (optional)
					-- https://github.com/neovim/nvim-lspconfig/pull/3232
					if server_name == "tsserver" then
						server_name = "ts_ls"
					end
					local capabilities = require("cmp_nvim_lsp").default_capabilities()
					require("lspconfig")[server_name].setup({

						capabilities = capabilities,
					})
				end,
			})
```

**Comment by justinmk** [comment]
Why not just change the "tsserver" item in `ensure_installed` to "ts_ls" ?

**Comment by ic-768** [comment]
> Why not just change the "tsserver" item in `ensure_installed` to "ts_ls" ?

Because that would tell mason to install the `ts_ls` package and no such package exists. It only has `tsserver`

**Comment by ic-768** [comment]
@SannanOfficial I don't use lsp_zero and I'm not getting any errors, so there might be some conflict with that plugin that needs fixing?

**Comment by SannanOfficial** [comment]
@ic-768 Perhaps, I will look intoi it. Thanks for the help.

**Comment by ofseed** [comment]
Originally, I planned to change the package name in mason-registry so that we could merge without many breaking changes, but I noticed a lot of pending pull requests in its repo (maybe the maintainer is busy now) so I did not.

Whenever you have a problem that is difficult to solve, I recommend switching to [vtsls](https://github.com/yioneko/nvim-vtsls). You will have almost the same experience because they are both `tsserver` under the hood.

**Comment by SannanOfficial** [comment]
@ofseed Spent about an hour trying to get this to work for me, couldn't at the moment so I will try and switch to vtsls as you suggested for the time being. Thanks.

**Comment by aw1875** [comment]
> ```
> if server_name == "tsserver" then
>     server_name = "ts_ls"
> end
> ```

Just came across this but you can also just use a simple one-liner to do the same thing:
```lua
server_name = server_name == 'tsserver' and 'ts_ls' or server_name
```

**Comment by jepeake** [comment]
`cd ~/.local/share/nvim/lazy/nvim-lspconfig`
`git checkout HEAD~1`

**Comment by padulkemid** [comment]
> > So, umm guys, I now get "tsserver is deprecated, use ts_ls instead" in my neovim after updating. How can I fix this? Do I need to edit some config file and change the name to ts_ls or what? I am asking this because mason doesn't have a separate ts_ls option to install within it.
> 
> I was also blindsided by this. Here's what I did ( not the full config but you can see how I handle the name change ):
> 
> ```
> 	{
> 		"williamboman/mason.nvim",
> 		dependencies = {
> 			"williamboman/mason-lspconfig.nvim",
> 			"neovim/nvim-lspconfig",
> 			"hrsh7th/nvim-cmp",
> 		},
> 		config = function()
> 			require("mason").setup()
> 			require("mason-lspconfig").setup({
> 				ensure_installed = {
> 					"lua_ls",
> 					"pyright",
> 					"ruff_lsp",
> 					"tsserver",
> 					"eslint",
> 					"tailwindcss",
> 					"emmet_language_server",
> 					"jsonls",
> 				},
> 			})
> 
> 			require("mason-lspconfig").setup()
> 
> 			-- automatically install ensure_installed servers
> 			require("mason-lspconfig").setup_handlers({
> 				-- Will be called for each installed server that doesn't have
> 				-- a dedicated handler.
> 				--
> 				function(server_name) -- default handler (optional)
> 					-- https://github.com/neovim/nvim-lspconfig/pull/3232
> 					if server_name == "tsserver" then
> 						server_name = "ts_ls"
> 					end
> 					local capabilities = require("cmp_nvim_lsp").default_capabilities()
> 					require("lspconfig")[server_name].setup({
> 
> 						capabilities = capabilities,
> 					})
> 				end,
> 			})
> ```

thanks it works, welp I think there will be a numerous config breaks later

**Comment by emanuele-em** [comment]
temporary fix for **vim-plug** users:
```lua
require('mason').setup()
require('mason-lspconfig').setup({
  ensure_installed = {'tsserver','pyright', 'jsonls', 'rust_analyzer'},
  handlers = {
    -- lsp_zero.default_setup,
    function(server_name)
      if server_name == 'tsserver' then
        server_name = 'ts_ls'
      else
        lsp_zero.default_setup(server_name)
      end
    end
  },
})
```

**Comment by cstromquist** [comment]
> `cd ~/.local/share/nvim/lazy/nvim-lspconfig` `git checkout HEAD~1`

Thanks! This is the only thing that worked for me. The other solution didn't fix the issue.

**Pull request merged**
