### PR TITLE
docs: update sumenko docs to add runtime files

### LINKED ISSUE #930: Printing package.(c)path on nightly build yields the path at build time
- `nvim --version`: neovim v0.5.0-dev+1166-g070e084a6
- Operating system/version: Ubuntu 20.04 (KDE Neon)
- Terminal name/version: Konsole 20.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Simply printing the values
```lua
print(package.path)
print(package.cpath)
```
reveals the problem

### Actual behaviour

The printed values only seem to be those that were used at build time, which for me were:

```
./?.lua;/home/joakker/.config/Dotfiles/nvim/neovim-nightly/.deps/usr/share/luajit-2.1.0-beta3/?.lua;/u
sr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/home/joakker/.config/Dotfiles/nvim/n
eovim-nightly/.deps/usr/share/lua/5.1/?.lua;/home/joakker/.config/Dotfiles/nvim/neovim-nightly/.deps/u
sr/share/lua/5.1/?/init.lua;/home/joakker/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua
;/home/joakker/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/joakker/.cache/
nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/joakker/.cache/nvim/packer_herero
cks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua

./?.so;/usr/local/lib/lua/5.1/?.so;/home/joakker/.config/Dotfiles/nvim/neovim-nightly/.deps/usr/lib/lu
a/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;/home/joakker/.cache/nvim/packer_hererocks/2.1.0-beta3/li
b/lua/5.1/?.so
```

### Expected behaviour

As it says in the documentation, that `package.path` reflect the lua directories in `runtimepath`.

This is a problem since using the `nvim-lspconfig` plugin, it is recommended to use `package.path` as the list of workspaces for the lsp, but if the value doesn't reflect `runtimepath`, then the server won't find the necessary plugins.

### PR DESCRIPTION
**Pull request by mjlbach**
closes #930

### CODE REVIEW

**Comment by mjlbach** [comment]
@nanotee @folke, I think this is correct.

**Comment by folke** [comment]
yep, looks good to me!
I'll run a quick test with the config myself here. give me a minute

**Comment by folke** [comment]
Getting proper completion on plugins. Works!

**Comment by folke** [comment]
I'm actually starting to think it might be enough to just have the following in your runtime path:
```lua
local runtime_path = {}
table.insert(runtime_path, "lua/?.lua")
table.insert(runtime_path, "lua/?/init.lua")
```

that `package.path` is probably not even needed. At least everything still works wihtout it

**Comment by mjlbach** [comment]
If you look here at least, they include the lua runtime files like we do (currently) in the sumneko docs:

https://github.com/sumneko/lua-language-server/wiki/Setting-without-VSCode#different-clients-load-settingjson-in-different-ways

**Comment by folke** [comment]
right, just leave it in then. Definitely works as expected

**Comment by nanotee** [comment]
Sorry about getting the original sumneko config wrong :sweat_smile:. The new suggested config works much better indeed

**Comment by mjlbach** [comment]
It's worked fine for me all this time! Just minor iteration

**Pull request merged**
