### PR TITLE
Add support for terraform-lsp

### PR DESCRIPTION
**Pull request by jcmuller**

### CODE REVIEW

**Comment by mjlbach** [comment]
Can you copy/paste the upstream explanation of the difference between terraform lsp and terraform ls into both servers documentation? Two separate commits please.

**Comment by jcmuller** [comment]
@mjlbach Done.

**Comment by mjlbach** [comment]
style lint still not passing

**Comment by jcmuller** [comment]
Ah. Sorry about that. Fixed.

**Pull request merged**
