### PR TITLE
fix(unocss): update filetypes

### PR DESCRIPTION
**Pull request by ryoppippi**
update filetypes of unocss lsp
Based on: 	
https://github.com/unocss/unocss/blob/35297359bf61917bda499db86e3728a7ebd05d6c/packages/vscode/src/autocomplete.ts#L12	
https://github.com/neovim/nvim-lspconfig/blob/dd329912c8d446240584a2dbcd3802af3a19105a/lua/lspconfig/server_configurations/tailwindcss.lua

### CODE REVIEW

**Comment by glepnir** [comment]
I am confused by similar behavior. Although this improves the out-of-the-box capabilities, it also bloats the table here. Many filetypes are not even in our built-in filetype support list. Maybe we should provide an append interface to achieve similar behavior instead of bloating it here.

**Comment by ryoppippi** [comment]
@glepnir Thaks
So how can I do this.
Actually it is okay to configure by myself.
Or just add `astro` is fine for me.

**Comment by glepnir** [comment]
Yes. Most of the time we recommend that users modify it locally. However, if the file type is supported by the built-in, it may be acceptable.

**Comment by ryoppippi** [comment]
OK, so in this PR, I just add the ft which are listed in the official vscode extension

**Comment by ryoppippi** [comment]
@glepnir Please check this out.

**Comment by justinmk** [comment]
needs a rebase since https://github.com/neovim/nvim-lspconfig/pull/3330

**Comment by ryoppippi** [comment]
Rebased done!

**Comment by justinmk** [comment]
try moving the file to `lua/lspconfig/configs/unocss.lua`

**Comment by ryoppippi** [comment]
@justinmk Hi! I just updated

**Pull request merged**
