### PR TITLE
Add solidity_ls solidity language server

### PR DESCRIPTION
**Pull request by edag94**
This language server for solidity provides autocompletion support that the only other solidity is doesn't provide (solang), and really improves the solidity dev experience

### CODE REVIEW

**Comment by mjlbach** [comment]
Can you rename the file to `solidity_ls.lua`? That is what it will show up as for `setup {}`

**Comment by edag94** [comment]
> Can you rename the file to `solidity_ls.lua`? That is what it will show up as for `setup {}`

Updated to solidity_ls.lua and also fixed my commit message

**Comment by evantancy** [comment]
hi, was wondering how do we pass cmd args to allow the LSP to properly recognize imports?

e.g. after installing openzeppelin contracts, inside vscode `settings.json` the lines `"solidity.packageDefaultDependenciesContractsDirectory": "contracts", "solidity.packageDefaultDependenciesDirectory": "node_modules"` prevents `import "@openzeppelin/contracts/token/ERC721/ERC721.sol";` from throwing "import not found" errors.

**Comment by itsdevcoffee** [comment]
### 

> hi, was wondering how do we pass cmd args to allow the LSP to properly recognize imports?
> 
> e.g. after installing openzeppelin contracts, inside vscode `settings.json` the lines `"solidity.packageDefaultDependenciesContractsDirectory": "contracts", "solidity.packageDefaultDependenciesDirectory": "node_modules"` prevents `import "@openzeppelin/contracts/token/ERC721/ERC721.sol";` from throwing "import not found" errors.

I'm running into a similar issue. Inside of Neovim it never resolves the import path correctly. It works fine inside of Vscode because I was able to pass in custom settings in the Vscode extension. I've tried everything at this point and I've hit a wall. I'm curious if anyone has a good solidity Lsp setup in Neovim they would be willing to share.

Screen Shot 2022-04-20 at 8 17 19 PM


Screen Shot 2022-04-20 at 7 33 19 PM

**Comment by evantancy** [comment]
@itsdevcoffee managed to get it working by defining a `remappings.txt` and placing it in the project root. (generated using https://book.getfoundry.sh/ by running `forge remappings > remappings.txt`
```
@openzeppelin/=lib/openzeppelin-contracts/
ds-test/=lib/ds-test/src/
solmate/=lib/solmate/src/
weird-erc20/=lib/solmate/lib/weird-erc20/src/
base64-sol/=lib/base64/
chiru-labs/ERC721A/=lib/ERC721A/contracts/
murky/=lib/murky/src/
forge-std/=lib/forge-std/src/
```
However, the LSPs don't really offer much right now... I'm currently using an extension called `vscode-neovim` (specifically with init.vim NOT init.lua) and it works great.

**Comment by nonogakhi** [comment]
Hey @evantancy congrats on making the imports work. Where do you refer to your remappings.txt? Maybe can you share your settings? here is mine:

```lua
return {
  cmd = { 'solidity-ls', '--stdio' },
  settings = {
    solidity = {
      remapping = {
        "ds-test/=lib/forge-std/lib/ds-test/src/",
        "diagnosticMode"
      },
    },
  },
}
```
This is also discussed in [solidity-ls](https://github.com/qiuxiang/solidity-ls/issues/3) and might be helpful

**Comment by evantancy** [comment]
@nonogakhi remappings are from [here](https://book.getfoundry.sh/projects/dependencies?highlight=remappings#remapping-dependencies) and my config dotfiles are [here](https://github.com/evantancy/.dotfiles/blob/9f32615f4f9f690029aa31181ad1463a22d7ab14/nvim/.config/nvim/lua/modules/config/lsp.lua#L88) so you can just keep remappings.txt in your repo and not have to keep changing your config

**Pull request merged**
