### PR TITLE
Do not set up nonexisting buffer

### PR DESCRIPTION
**Pull request by przepompownia**
It can occur after (LSP) renaming the class without opening it (e.g. on its some reference).

### CODE REVIEW

**Comment by mjlbach** [comment]
Can you give me a minimal repro that cause this?

**Comment by przepompownia** [comment]
It can be not trivial but I'll try.

**Comment by przepompownia** [comment]
https://github.com/przepompownia/nvim-test-lspconfig - please look how `make nonexisting-buffer` works or simply run it. 
image

**Comment by przepompownia** [comment]
It's still present on the above example.

**Comment by justinmk** [comment]
on_attach is a nontrivial callback so it makes sense to check the bufnr.

**Comment by przepompownia** [comment]
Thanks!

**Pull request merged**
