### PR TITLE
fix(denols): add package_json

### PR DESCRIPTION
**Pull request by tamago324**
Added the path to package.json.

Please check it.

### CODE REVIEW

**Comment by mjlbach** [comment]
Are you validating these? Most of this looks like options for vscode, not for sending to deno's language server.

**Comment by tamago324** [comment]
I'm sorry. I haven't verified it.
We have not tested other language servers, so we will do so and create the PR again.

**Comment by mjlbach** [comment]
It's fine, just test the already open PRs and let me know if the settings are relevant, and I will merge if that is the case.

**Comment by tamago324** [comment]
Yes, sir.
It may take some time, but I'll verify and get back to you.
Thank you.

**Comment by tamago324** [comment]
I don't know the details of the Rust code, but according to the [deno server code](https://github.com/denoland/deno/blob/0888ba7a8db33ee01f57679308e7e8c4eea108e9/cli/lsp/config.rs#L148), the vscode_deno setting seems to be correct.
Here is the result.
Also, we have not checked all the settings, but we have confirmed that some of them work correctly.

> It is assumed that `YES` is the correct setting value and `NO` is the setting value for VSCode only.

```
YES "deno.cache",
YES "deno.codeLens.implementations",
YES "deno.codeLens.references",
YES "deno.codeLens.referencesAllFunctions",
YES "deno.codeLens.test",
NO "deno.codeLens.testArgs",
YES "deno.config",
YES "deno.enable",
YES "deno.importMap",
YES "deno.internalDebug",
YES "deno.lint",
NO "deno.path",
YES "deno.suggest.autoImports",
YES "deno.suggest.completeFunctionCalls",
YES "deno.suggest.imports.autoDiscover",
YES "deno.suggest.imports.hosts",
YES "deno.suggest.names",
YES "deno.suggest.paths",
YES "deno.unstable"
```

**Comment by tamago324** [comment]
Thank you for merging!

**Pull request merged**
