### PR TITLE
Add support for Lua language server alloyed_lua

### PR DESCRIPTION
**Pull request by ojroques**
Add a new language server for Lua: [here's the repo](https://github.com/Alloyed/lua-lsp). I find `sumneko_lua` way too complicated to install so I figured I'd use this one instead.

### CODE REVIEW

**Comment by saadparwaiz1** [comment]
shouldn't the root_dir function look for .luacheckrc and .luacompleterc?

**Comment by ojroques** [comment]
Yes good point. I've updated `root_dir` accordingly.

**Comment by tssm** [comment]
Hey folks, I would like to know if this is going to be merged? I was working on the same without realizing someone already opened a PR

**Comment by mjlbach** [comment]
The main reason I haven't merged this, is because currently alloyed is not a full featured language server, and we already offer sumneko. Symbol/signature/references aren't implemented, it's a bit slower, and the completion results are IMO worse. It also hasn't been updated in 3+ months.

I guess if there's a big demand for this we can merge it, but generally we tend to only have language servers that are either 

1. The only available language server for the respective language
2. Mostly full implementation of the lsp spec/actively developed

**Comment by mjlbach** [comment]
I'm going to close since there hasn't been any activity on the alloyed-lsp repo, but feel free to reopen if the project picks back up again :)

**Pull request closed without merging**
