### PR TITLE
[WIP] Generate web documentation with mkdocs (#1027)

### PR DESCRIPTION
**Pull request by andersevenrud**
The following PR introduces some changes in order to generate markdown files that is optimized for use with mkdocs. 

Preview: https://andersevenrud.github.io/nvim-lspconfig-web/languages/pyls/

TODO:

- [ ] Automated sorting of sidebar navigation by article title (H1). mkdocs uses the filename to sort so right now this is statically defined via configuration file.
- [ ] Improve language names assigned in the metadata
- [ ] ... see discussion topics below ...

Changes:

- Changes language markdown templates
- Adds `language_name` to the configuration files (ex.: `Python`)
- Updates `docgen` to produce individual markdown files in addition to `CONFIG.md`
- Added [`MkDocs`](https://www.mkdocs.org/) configuration

If you wanna test this yourself:

```shell
pip install mkdocs-material # this also installs peer dependencies
./scripts/docgen.sh
mkdocs serve
```

Some things to discuss:

1. The template changes makes `CONFIG.md` a bit more verbose. Should there be two types of documentation here, i.e. web and repo ? Or:
2. Phase out `CONFIG.md` and direct users to the individual files?
3. The `<details>` elements did not support markdown, so they were removed. But because of the template changes this is maybe not much of an issue?
4. The contents of ex. `README.md` has now been duplicated, which is probably not ideal.

Relevant issues:

- https://github.com/neovim/nvim-lspconfig/issues/1027

### CODE REVIEW

**Comment by mjlbach** [comment]
bad bot

**Comment by andersevenrud** [comment]
> bad bot

It's my fault. I did some rebasing and it turns out I was not using upstream, so something went a bit wrong here :joy: I'll ping to re-open when I have it sorted out.

**Comment by andersevenrud** [comment]
@mjlbach Should be in order now... but I don't see any changes in this UI when I force pushed. But maybe it's just because the PR was closed ? :)

**Comment by andersevenrud** [comment]
I decided to scratch this PR because things got a bit messed up, and I changed things quite a bit. Sorry about the inconvenience.

#1036

**Pull request closed without merging**
