### PR TITLE
add default for kotlin-language-server cmd

### PR DESCRIPTION
**Pull request by jan-xyz**
It is not that easy to find out what needs to happen for the language server command to be picked up. I think this can help a lot of newcomers to quickly get started with Kotlin and the language client.

### CODE REVIEW

**Comment by justinmk** [comment]
hmm. i retried the builds but they keep failing...

**Comment by jan-xyz** [comment]
It's weird, the linter fails because of a permission problem, it seems, and the test on macOS because some dependencies area already installed :-/ Is there a way for me to run the linter locally at least?

**Comment by justinmk** [comment]
the permissions issue was fixed, please rebase...

**Comment by justinmk** [comment]
CI should be fixed if you rebase.

@thchha was there a reason for not including a default `cmd` ? What config are you using personally?

**Comment by jan-xyz** [comment]
@justinmk, I rebased and it worked :)

**Comment by h-michael** [comment]
@jan-xyz Thank you for your PR.
I added support Windows commit to your PR and merged it.

**Pull request closed without merging**
