### PR TITLE
Add support for Zig language server

### PR DESCRIPTION
**Pull request by haze**
https://github.com/zigtools/zls

### CODE REVIEW

**Review by ellisonleao — APPROVED** [review]

**Comment by ellisonleao** [comment]
@teto any thoughts on getting this merged ? Current code is breaking due to old imports still being used

**Comment by haze** [comment]
@teto  bro ??? :3

**Comment by mjlbach** [comment]
Isn't this already merged? There's a zls.lua on master

**Comment by ellisonleao** [comment]
@mjlbach there's a previous merge but with old code, this one is the updated version pretty much. We just need to get it merged

**Comment by mjlbach** [comment]
There is already a zls.lua for zig, it's just in the wrong place with old imports. I made this PR to fix the issue. This PR as it stands needs to be rebased, and it also reimplements zls (so there would be two zls configs if this were merged).

See: https://github.com/neovim/nvim-lspconfig/pull/459

**Comment by ellisonleao** [comment]
as i've said, old code. Either way is fine, we just need to get some implementation up to date

**Comment by haze** [comment]
ok watch this

**Comment by mjlbach** [comment]
#459 was merged, so ZLS should be working now. As I see it now, this PR mainly:

1) Removes zir from the filetypes 
2) Removes root_pattern detection for .git and zls.json
3) Changes the readme description.

Are the latter two necessary? I can't find any information on ZLS repo about zir.

**Comment by haze** [comment]
Let’s leave it at that then.

**Pull request closed without merging**
