### PR TITLE
Allow bashls to work with Makefile and Zsh script

### PR DESCRIPTION
**Pull request by rekaerst**
Allow bash-language-server to work with Makefile and Zsh scripts since their commands are similar

### CODE REVIEW

**Comment by mjlbach** [comment]
I don't think we should add this as a default, but users can add this locally in their config if they understand that some diagnostics are will be incorrect

**Comment by rekaerst** [comment]
IIRC bashls doesn't have diagnostics.

**Comment by mjlbach** [comment]
According to the readme, it does.

**Comment by rekaerst** [comment]
My apology.
This could be closed I think.

**Pull request closed without merging**
